In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import shutil
import csv
import math
import json
import ast
import cv2
import seaborn as sns
import logging

In [2]:
import warnings

# Ignore warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('panel_data_fin.csv')

## Analysis 0

In [5]:
df

,time,Thumb_L_sum,Thumb_R_sum,LE_speed_mean,LE_speed_median,LE_pos_change_sum,LE_pos_change_mean,LE_pos_change_median,Head_Speed_mean,Head_Speed_median,...,IndTrig_R,HandTrig_L,HandTrig_R,Thumb_L_x,Thumb_R_x,Thumb_L_y,Thumb_R_y,user_id,game_id,order
0,0,0.000000,3.594337,0.127828,0.090655,2.316057,0.020865,0.012802,0.172464,0.125845,...,0,32,0,0,3,0,3,5,1,2
1,1,33.093972,62.157799,0.063716,0.036334,3.967072,0.013448,0.005704,0.063247,0.036310,...,12,48,15,64,43,66,40,5,1,2
2,2,46.027865,90.608110,0.068397,0.042165,3.758526,0.009813,0.006048,0.067828,0.040388,...,4,62,37,100,63,93,70,5,1,2
3,3,18.430878,5.229467,0.068757,0.038978,3.775398,0.010068,0.005633,0.069725,0.037508,...,272,71,127,14,7,11,5,5,1,2
4,4,26.719036,1.597837,0.150314,0.117524,8.961758,0.022349,0.017352,0.153218,0.125837,...,203,27,157,22,5,21,5,5,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,103.000739,94.874378,0.034958,0.021215,2.608618,0.005598,0.003259,0.031584,0.021257,...,1,22,0,171,54,168,55,147,34,1
2930,8,53.928953,36.710560,0.043327,0.026262,2.421957,0.007295,0.004128,0.044183,0.025836,...,24,10,13,98,19,118,22,147,34,1
2931,9,45.495983,42.703410,0.026860,0.021454,1.126662,0.004471,0.003622,0.027040,0.021753,...,46,2,0,95,28,109,26,147,34,1
2932,10,17.765149,10.020055,0.123650,0.077568,5.506467,0.018858,0.012262,0.124227,0.078281,...,27,112,1,41,7,31,6,147,34,1
2933,11,6.148178,0.000000,0.063157,0.033172,1.521158,0.010074,0.005324,0.063689,0.038167,...,0,4,0,8,0,4,0,147,34,1

In [6]:
# df[df['change in brightness_mean']>0]

### aux1

In [38]:
game_abbs={'Earth_Gym': 1,
 'Wild_Quest': 2,
 'Roommate': 3,
 'Waffle_Restaurant': 4,
 'Superhero_Arena': 5,
 'Army_Men': 6,
 'Bobber_Bay_Fishing': 7,
 'Citadel': 8,
 'Mars_Miners': 9,
 'American_Idol': 10,
 'Kawaii_Daycare': 11,
 'Giant_Paddle_Golf': 12,
 'City_Parkour': 13,
 'Wake_the_Robot': 14,
 'The_aquarium': 15,
 'UFO_crash_site_venue': 16,
 'Kowloon': 17,
 'Arena_Clash': 18,
 'Scifi_Sandbox': 19,
 'Super_Rumble': 20,
 'Slash_RPG': 21,
 'Pirate_Life': 22,
 'Zombie': 23,
 'Horizon_Boxing': 24,
 'VR_Classroom': 25,
 'Venues': 26,
 'Metdonalds': 27,
 '3D_Play_House': 28,
 'Out_Of_Control': 29,
 'Geometry_Gunners': 30,
 'Barnyard': 31,
 'Canyon_Runners': 32,
 'Titanic_Simulation': 33,
 'Creature_Feature': 34}

In [39]:
dev_rating={}

In [40]:
rating=pd.read_csv("/home/dinithi/game_intensity.csv")

In [41]:
import pandas as pd

# Assuming your dataset is stored in a DataFrame named df
data = rating.set_index('Game').to_dict()['Intensity']

# Convert the data to JSON format
json_data = {game: intensity for game, intensity in data.items()}

# Print or save the JSON data
print(json_data)

{'Barbie': 'C', 'Escape_Puzzle_Mansion': 'C', 'Spy_School': 'I', 'Octopus_Bash': 'M', 'Circle_Kawaii': 'C', 'Delivery_Dash': 'C', 'New_Olympus': 'C', 'Junior_Chef': 'C', 'Puddles_Theme_Park': 'C', 'Land_Beyond': 'M', 'Red_Dead': 'M', 'Metdonalds': 'C', 'Metablocks_Adventure': 'C', 'Kawaii_Daycare': 'C', 'Venues': 'C', 'Mech_Playground': 'I', 'Mars_Miners': 'M', 'Puddles_Water_Park': 'C', 'Kawaii_Playroom': 'C', 'Roommate': 'M', 'Walking_Dead': 'C', 'Barnyard': 'C', 'Flight_Squad': 'M', 'The_aquarium': 'C', 'Kawaii_Fire_Station': 'C', 'Arena_Clash': 'M', 'Wood_Warehouse': 'C', 'Frisbee_Golf': 'C', 'Wake_the_Robot': 'C', 'VR_Bank': 'C', 'NBA_Arena': 'C', 'VR_Classroom': 'C', 'Born_With_Power': 'I', 'Horizon_Boxing': 'I', 'Slash': 'C', 'Bonnie_Revenge': 'M', 'Kowloon': 'M', 'Out_Of_Control': 'C', 'Titanic_Simulation': 'C', 'Earth_Gym': 'M', 'Retro_Zombie': 'M', 'Super_Rumble': 'M', 'Water_Battling': 'M', 'Kawaii_House': 'C', 'Fun_House': 'C', 'Giant_Paddle_Golf': 'C', 'Creature_Feature': 'M', 'Mega_Tasty_BBQ': 'C', 'Wild_Quest': 'M', 'UFO_crash_site_venue': 'C', 'Zombie': 'C', 'Kawaii_Urgent_Care': 'C', 'Western_Skies_RPG': 'M', 'Airplane_Obstacle': 'C', 'American_Idol': 'C', 'Army_Men': 'C', 'Fight_the_Night': 'M', 'Canyon_Runners': 'M', 'MB_Deja_Vu': 'C', 'Bobber_Bay_Fishing': 'C', 'Live_Sandbox': 'C', '98_Escapes': 'M', 'HoverTag': 'I', 'Citadel': 'M', 'City_Parkour': 'I', 'Meta_Pizza_Hut_Classic': 'C', 'Wizard_Sandbox': 'M', '3D_Play_House': 'I', 'Scifi_Sandbox': 'C', 'Cartoon_Wars': 'C', 'Zoo_Chef_Challenge': 'C', 'Kawaii_Police_Station': 'C', 'Waffle_Restaurant': 'C', 'Breakneck_Canyon': 'M', 'Slash_RPG': 'I', 'Sky_High_Trampoline_Park': 'I', 'Geometry_Gunners': 'C', 'Jail_Simulator': 'C', 'Pirate_Life': 'C', 'Superhero_Arena': 'M', 'Halloween_Wars': 'C', 'Man_of_Moon_Mountain': 'C'}

In [42]:
for i in game_abbs.keys():
    dev_rating[game_abbs[i]]=json_data[i]

In [43]:
dev_rating

{1: 'M',
 2: 'M',
 3: 'M',
 4: 'C',
 5: 'M',
 6: 'C',
 7: 'C',
 8: 'M',
 9: 'M',
 10: 'C',
 11: 'C',
 12: 'C',
 13: 'I',
 14: 'C',
 15: 'C',
 16: 'C',
 17: 'M',
 18: 'M',
 19: 'C',
 20: 'M',
 21: 'I',
 22: 'C',
 23: 'C',
 24: 'I',
 25: 'C',
 26: 'C',
 27: 'C',
 28: 'I',
 29: 'C',
 30: 'C',
 31: 'C',
 32: 'M',
 33: 'C',
 34: 'M'}

In [44]:
game_id=df2['game_id'].to_list()

In [45]:
Intensity=[]
for i in game_id:
    Intensity.append(dev_rating[i])

In [46]:
# Intensity

In [47]:
df2['Intensity'] = Intensity

In [48]:
df2

,time,MS_rating,Thumbstick_L,Thumbstick_R,Eye_Speed,Head_Speed,diff_Head_Eye_yaw,diff_Head_Eye_roll,diff_Head_Eye_mean,Index_Trig_L,...,camera_yaw,camera speed,text_presence,brightness_change,Buttons,Jumping,user_id,game_id,order,Intensity
1,1,1.0,33.093972,62.157799,0.063716,0.063247,0.039889,0.166769,0.089614,8,...,0.171433,107.561279,170.0,3.539671,10,10,5,1,2,M
2,2,1.0,46.027865,90.608110,0.068397,0.067828,0.070310,0.159780,0.088873,0,...,0.118171,17.435567,374.0,5.606859,6,6,5,1,2,M
3,3,1.0,18.430878,5.229467,0.068757,0.069725,0.131197,0.508019,0.075576,23,...,0.088050,10.550932,338.0,4.198118,8,0,5,1,2,M
4,4,1.0,26.719036,1.597837,0.150314,0.153218,0.150352,0.257278,0.079519,18,...,0.107537,21.359123,345.0,8.341409,0,0,5,1,2,M
5,5,1.0,47.349634,26.812417,0.100103,0.100336,0.093609,0.267467,0.080504,80,...,0.096619,11.013235,410.0,7.514897,10,10,5,1,2,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,2.0,103.000739,94.874378,0.034958,0.031584,0.016483,0.148175,0.108648,27,...,0.227713,8.584673,466.0,2.331750,5,0,147,34,1,M
2930,8,5.0,53.928953,36.710560,0.043327,0.044183,0.046547,0.142530,0.115478,18,...,0.328727,10.933816,332.0,3.597338,8,1,147,34,1,M
2931,9,4.0,45.495983,42.703410,0.026860,0.027040,0.007830,0.081415,0.103795,0,...,0.226711,13.106737,252.0,2.057278,3,2,147,34,1,M
2932,10,3.0,17.765149,10.020055,0.123650,0.124227,0.077299,0.278264,0.132923,0,...,0.265106,11.402999,292.0,1.317426,1,0,147,34,1,M
2933,11,5.0,6.148178,0.000000,0.063157,0.063689,0.123426,0.268676,0.187580,0,...,0.221347,7.815273,151.0,2.934065,0,0,147,34,1,M

In [16]:
# df.to_csv('panel_data_1.csv', index=False)

In [17]:
df['MS_rating_sum']

0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
       ...
2929    2.0
2930    5.0
2931    4.0
2932    3.0
2933    5.0
Name: MS_rating_sum, Length: 2934, dtype: float64

In [18]:
print(df['Intensity'].unique())

['M' 'C' 'I']

In [19]:
for i in df.columns:
    print(i, end=' ')

time Thumb_L_sum Thumb_R_sum LE_speed_mean LE_speed_median LE_pos_change_sum LE_pos_change_mean LE_pos_change_median Head_Speed_mean Head_Speed_median Head_pos_change_sum Head_pos_change_mean Head_pos_change_median Head_Velocity_Change_mean Head_Velocity_Change_median Head_AngVel_Change_mean Head_AngVel_Change_median c_speed_mean c_speed_median text_presence_sum change in brightness_mean change in brightness_median diff_HE_yaw_sum diff_HE_yaw_mean diff_HE_yaw_median diff_HE_roll_sum diff_HE_roll_mean diff_HE_roll_median diff_HE_pitch_sum diff_HE_pitch_mean diff_HE_pitch_median c_change_pitch_sum c_change_pitch_mean c_change_pitch_median c_change_roll_sum c_change_roll_mean c_change_roll_median c_change_yaw_sum c_change_yaw_mean c_change_yaw_median MS_rating_sum Buttons A_Pressed IndTrig_L IndTrig_R HandTrig_L HandTrig_R Thumb_L_x Thumb_R_x Thumb_L_y Thumb_R_y user_id game_id order Intensity

In [ ]:
Thumb_L_sum Thumb_R_sum LE_speed_mean LE_speed_median LE_pos_change_sum LE_pos_change_mean LE_pos_change_median 
Head_Speed_mean Head_Speed_median Head_pos_change_sum Head_pos_change_mean Head_pos_change_median 
Head_Velocity_Change_mean Head_Velocity_Change_median Head_AngVel_Change_mean Head_AngVel_Change_median 
c_speed_mean c_speed_median text_presence_sum diff_HE_yaw_sum diff_HE_yaw_mean diff_HE_yaw_median 
diff_HE_roll_sum diff_HE_roll_mean diff_HE_roll_median diff_HE_pitch_sum diff_HE_pitch_mean 
diff_HE_pitch_median c_change_pitch_sum c_change_pitch_mean c_change_pitch_median c_change_roll_sum 
c_change_roll_mean c_change_roll_median c_change_yaw_sum c_change_yaw_mean c_change_yaw_median  
Buttons A_Pressed IndTrig_L IndTrig_R HandTrig_L HandTrig_R Thumb_L_x Thumb_R_x Thumb_L_y Thumb_R_y order

In [9]:


# # Calculate the correlation matrix
# correlation_matrix = df.corr()

# print(correlation_matrix)

In [26]:
# plt.figure(figsize=(25, 25))
# sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
# plt.title('Correlation Matrix')
# plt.show()

In [27]:
correlation_matrix = df.corr()

# Find columns to drop based on correlation greater than 0.8
columns_to_drop = set()
for i in range(len(correlation_matrix.columns)):
    for j in range(i):
        if abs(correlation_matrix.iloc[i, j]) > 0.8:
            colname = correlation_matrix.columns[i]
            columns_to_drop.add(colname)

# Drop columns from DataFrame
df = df.drop(columns=columns_to_drop)

print(df)

      time  Thumb_L_sum  Thumb_R_sum  LE_speed_mean  LE_pos_change_mean  \
0        0     0.000000     3.594337       0.127828            0.020865
1        1    33.093972    62.157799       0.063716            0.013448
2        2    46.027865    90.608110       0.068397            0.009813
3        3    18.430878     5.229467       0.068757            0.010068
4        4    26.719036     1.597837       0.150314            0.022349
...    ...          ...          ...            ...                 ...
2929     7   103.000739    94.874378       0.034958            0.005598
2930     8    53.928953    36.710560       0.043327            0.007295
2931     9    45.495983    42.703410       0.026860            0.004471
2932    10    17.765149    10.020055       0.123650            0.018858
2933    11     6.148178     0.000000       0.063157            0.010074

      c_speed_mean  text_presence_sum  change in brightness_mean  \
0         2.562619                0.0                        0.0
1       107.561279              170.0                        0.0
2        17.435567              374.0                        0.0
3        10.550932              338.0                        0.0
4        21.359123              345.0                        0.0
...            ...                ...                        ...
2929      8.584673              466.0                        0.0
2930     10.933816              332.0                        0.0
2931     13.106737              252.0                        0.0
2932     11.402999              292.0                        0.0
2933      7.815273              151.0                        0.0

      change in brightness_median  diff_HE_yaw_sum  ...  A_Pressed  IndTrig_L  \
0                             0.0       -11.401636  ...          0          0
1                             0.0        -4.638611  ...         10          8
2                             0.0        15.245216  ...          6          0
3                             0.0        -7.271886  ...          0         23
4                             0.0        24.435582  ...          0         18
...                           ...              ...  ...        ...        ...
2929                          0.0         0.001036  ...          0         27
2930                          0.0         7.121789  ...          1         18
2931                          0.0        -0.779276  ...          2          0
2932                          0.0        -0.283591  ...          0          0
2933                          0.0        -2.232034  ...          0          0

      IndTrig_R  HandTrig_L  HandTrig_R  Thumb_L_x  user_id  game_id  order  \
0             0          32           0          0        5        1      2
1            12          48          15         64        5        1      2
2             4          62          37        100        5        1      2
3           272          71         127         14        5        1      2
4           203          27         157         22        5        1      2
...         ...         ...         ...        ...      ...      ...    ...
2929          1          22           0        171      147       34      1
2930         24          10          13         98      147       34      1
2931         46           2           0         95      147       34      1
2932         27         112           1         41      147       34      1
2933          0           4           0          8      147       34      1

      Intensity
0             M
1             M
2             M
3             M
4             M
...         ...
2929          M
2930          M
2931          M
2932          M
2933          M

[2934 rows x 35 columns]

In [28]:
df

,time,Thumb_L_sum,Thumb_R_sum,LE_speed_mean,LE_pos_change_mean,c_speed_mean,text_presence_sum,change in brightness_mean,change in brightness_median,diff_HE_yaw_sum,...,A_Pressed,IndTrig_L,IndTrig_R,HandTrig_L,HandTrig_R,Thumb_L_x,user_id,game_id,order,Intensity
0,0,0.000000,3.594337,0.127828,0.020865,2.562619,0.0,0.0,0.0,-11.401636,...,0,0,0,32,0,0,5,1,2,M
1,1,33.093972,62.157799,0.063716,0.013448,107.561279,170.0,0.0,0.0,-4.638611,...,10,8,12,48,15,64,5,1,2,M
2,2,46.027865,90.608110,0.068397,0.009813,17.435567,374.0,0.0,0.0,15.245216,...,6,0,4,62,37,100,5,1,2,M
3,3,18.430878,5.229467,0.068757,0.010068,10.550932,338.0,0.0,0.0,-7.271886,...,0,23,272,71,127,14,5,1,2,M
4,4,26.719036,1.597837,0.150314,0.022349,21.359123,345.0,0.0,0.0,24.435582,...,0,18,203,27,157,22,5,1,2,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,103.000739,94.874378,0.034958,0.005598,8.584673,466.0,0.0,0.0,0.001036,...,0,27,1,22,0,171,147,34,1,M
2930,8,53.928953,36.710560,0.043327,0.007295,10.933816,332.0,0.0,0.0,7.121789,...,1,18,24,10,13,98,147,34,1,M
2931,9,45.495983,42.703410,0.026860,0.004471,13.106737,252.0,0.0,0.0,-0.779276,...,2,0,46,2,0,95,147,34,1,M
2932,10,17.765149,10.020055,0.123650,0.018858,11.402999,292.0,0.0,0.0,-0.283591,...,0,0,27,112,1,41,147,34,1,M
2933,11,6.148178,0.000000,0.063157,0.010074,7.815273,151.0,0.0,0.0,-2.232034,...,0,0,0,4,0,8,147,34,1,M

In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import shutil
import csv
import math
import json
import ast
import cv2


dtypes = {
    'v_matrix': 'str',
    'camera_name': 'str',
    # 'object_name' : 'str',
    # 'bounds': 'str',
    # 'm_matrix': 'str'
    # define other columns as needed
}
# Selecting rows within the ratings 

# Define a function to calculate quaternion rotation change
def calculate_rotation_change(curr_quaternion, prev_quaternion):
    dot_products = np.sum(curr_quaternion * prev_quaternion, axis=1)
    angle_changes = 2 * np.arccos(np.abs(dot_products))
    return angle_changes

# Define a function to calculate magnitude change of position
def calculate_speed(curr_x, curr_y, curr_z, t1, prev_x, prev_y, prev_z, t2):
    pos_change= ((curr_x - prev_x)**2 + (curr_y - prev_y)**2 + (curr_z - prev_z)**2)**0.5
    speed= pos_change*1000/(t1-t2)
    return speed

def calculate_position_change(curr_x, curr_y, curr_z, prev_x, prev_y, prev_z):
    return ((curr_x - prev_x)**2 + (curr_y - prev_y)**2 + (curr_z - prev_z)**2)**0.5
    

def calculate_magnitude_dir(curr_x, curr_y, prev_x, prev_y):
    magnitude= ((curr_x - prev_x)**2 + (curr_y - prev_y)**2)**0.5
    dir_x= (curr_x - prev_x)/magnitude
    dir_y= (curr_y - prev_y)/magnitude
    return magnitude,dir_x, dir_y

def extract_position_and_euler_angles_from_matrix(matrix):
    matrix = np.array(matrix).reshape(4, 4).T
    # print(matrix)
    x,y,z = matrix[:3, 3]
    rotation_matrix = matrix[:3, :3]
    yaw = np.arctan2(rotation_matrix[1, 0], rotation_matrix[0, 0])
    pitch = np.arcsin(-rotation_matrix[2, 0])
    roll = np.arctan2(rotation_matrix[2, 1], rotation_matrix[2, 2])

    return x,y,z, yaw, pitch, roll

def check_for_text(lst):
    ans=0
    if 'TextMeshPro' in lst:
        ans=1
    else:
        ans=0
    return ans

def calculate_brightness(image):
    # Convert image to grayscale
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    # Calculate average pixel intensity
    avg_intensity = np.mean(gray_image)
    return avg_intensity

def detect_lighting_changes(images):
    # Calculate average pixel intensity for each image
    # image = image.astype('uint8')
    brightness_values = []
    for image in images:
        if image is not None:
            brightness_values.append(calculate_brightness(image.astype('uint8')))
        else:
            # Handle the case where the image is None
            brightness_values.append(0)
    brightness_changes = [abs(brightness_values[i] - brightness_values[i-1]) for i in range(1,len(brightness_values))]
    brightness_changes.insert(0, 0)
    return brightness_changes



def quaternion_to_euler(row):
    x, y, z, w = row
    # Calculate roll
    roll = math.atan2(2 * (w * x + y * z), 1 - 2 * (x**2 + y**2))
    
    # Calculate pitch
    sin_pitch = 2 * (w * y - z * x)
    if abs(sin_pitch) >= 1:
        pitch = math.copysign(math.pi / 2, sin_pitch)
    else:
        pitch = math.asin(sin_pitch)
    
    # Calculate yaw
    yaw = math.atan2(2 * (w * z + x * y), 1 - 2 * (y**2 + z**2))
    
    return pd.Series({'le_roll': roll, 'le_pitch': pitch, 'le_yaw': yaw})


def clean(df_sess_path):
    df_cleaned=[]
    df_trimmed=[]
    df_sess_path_df=os.path.join(df_sess_path,'data_file.csv')
    df_sess=pd.read_csv(df_sess_path_df, dtype=dtypes)
    df_sess_path_vid=os.path.join(df_sess_path,'video')
    # df_cleaned=[]
    # Find the index of the first and last non-null rating
    first_rating_index = df_sess['MS_rating'].first_valid_index()
    last_rating_index = df_sess['MS_rating'].last_valid_index()

    # Slice the DataFrame to retain rows only between the first and last rating
    df_trimmed = df_sess.loc[first_rating_index-1:last_rating_index]
    # print("nan_count = ", df_trimmed['Buttons'].isna().sum())
    df_trimmed.reset_index(drop=True, inplace=True)

    #drop the columns without the control ratings/ fill the rating with mode of each column
    col_to_fill_mode=[ 'Buttons','IndexTrigger', 'HandTrigger','Thumbstick','left_eye','right_eye','camera_name','v_matrix','p_matrix','object_name']
    col_to_fill_median=[ 'Touches','NearTouches']
    df_cleaned=df_trimmed


    # declare the columns to be filled with mode and medians
    modes = df_cleaned[col_to_fill_mode].mode().iloc[0]
    medians = df_cleaned[col_to_fill_median].median()
    # print(modes)

    df_cleaned[col_to_fill_mode]=df_cleaned[col_to_fill_mode].fillna(modes)
    df_cleaned[col_to_fill_median]=df_cleaned[col_to_fill_median].fillna(medians)

    df_cleaned[['IndTrig_L', 'IndTrig_R']] = df_cleaned['IndexTrigger'].apply(lambda x: pd.Series(ast.literal_eval(x)))
    df_cleaned[['HandTrig_L', 'HandTrig_R']] = df_cleaned['HandTrigger'].apply(lambda x: pd.Series(ast.literal_eval(x)))
    # df_cleaned[['IndTrig_L', 'IndTrig_R','HandTrig_L', 'HandTrig_R']] = df_cleaned[['IndTrig_L', 'IndTrig_R','HandTrig_L', 'HandTrig_R']].round()

    # Apply the function to calculate magnitude for each row
    df_cleaned[['PrevX_L', 'PrevY_L', 'PrevX_R', 'PrevY_R']] = df_cleaned['Thumbstick'].apply(lambda x: pd.Series(ast.literal_eval(x)))

    # Calculate tmagnitude for left hand and right hand
    df_cleaned['Thumb_L'] = calculate_magnitude_dir(df_cleaned['PrevX_L'], df_cleaned['PrevY_L'], df_cleaned['PrevX_L'].shift(1), df_cleaned['PrevY_L'].shift(1))[0]
    df_cleaned['Thumb_R'] = calculate_magnitude_dir(df_cleaned['PrevX_R'], df_cleaned['PrevY_R'], df_cleaned['PrevX_R'].shift(1), df_cleaned['PrevY_R'].shift(1))[0]
    
    df_cleaned['Thumb_L_x'] = calculate_magnitude_dir(df_cleaned['PrevX_L'], df_cleaned['PrevY_L'], df_cleaned['PrevX_L'].shift(1), df_cleaned['PrevY_L'].shift(1))[1]
    df_cleaned['Thumb_R_x'] = calculate_magnitude_dir(df_cleaned['PrevX_R'], df_cleaned['PrevY_R'], df_cleaned['PrevX_R'].shift(1), df_cleaned['PrevY_R'].shift(1))[1]
    
    df_cleaned['Thumb_L_y'] = calculate_magnitude_dir(df_cleaned['PrevX_L'], df_cleaned['PrevY_L'], df_cleaned['PrevX_L'].shift(1), df_cleaned['PrevY_L'].shift(1))[2]
    df_cleaned['Thumb_R_y'] = calculate_magnitude_dir(df_cleaned['PrevX_R'], df_cleaned['PrevY_R'], df_cleaned['PrevX_R'].shift(1), df_cleaned['PrevY_R'].shift(1))[2]
    
    
    #Gaze

    # print("nan_count = ", df_cleaned['left_eye'].isna().sum())
    # Apply the function to extract quaternion and position components for each row
    df_cleaned[['le_x', 'le_y', 'le_z', 'le_w', 'le_p1', 'le_p2', 'le_p3']] = df_cleaned['left_eye'].apply(lambda x: pd.Series(ast.literal_eval(x)))
    
    # df_cleaned[['le_roll', 'le_pitch', 'le_yaw']]= quaternion_to_euler(df_cleaned[['le_x', 'le_y', 'le_z', 'le_w']].values)
    df_cleaned[['le_roll', 'le_pitch', 'le_yaw']] = df_cleaned[['le_x', 'le_y', 'le_z', 'le_w']].apply(quaternion_to_euler, axis=1)

    # print(df_cleaned[['x', 'y', 'z', 'w']].values)
    # Calculate rotation change and position change
    df_cleaned['LE_speed'] = calculate_speed(df_cleaned['le_p1'], df_cleaned['le_p2'], df_cleaned['le_p3'], df_cleaned['timestamp'], df_cleaned['le_p1'].shift(1), df_cleaned['le_p2'].shift(1), df_cleaned['le_p3'].shift(1), df_cleaned['timestamp'].shift(1))
    df_cleaned['LE_pos_change']=calculate_position_change(df_cleaned['le_p1'], df_cleaned['le_p2'], df_cleaned['le_p3'], df_cleaned['le_p1'].shift(1), df_cleaned['le_p2'].shift(1), df_cleaned['le_p3'].shift(1))
    
    df_cleaned[['re_x', 're_y', 're_z', 're_w', 're_p1', 're_p2', 're_p3']] = df_cleaned['right_eye'].apply(lambda x: pd.Series(ast.literal_eval(x)))
    # print(df_cleaned[['x', 'y', 'z', 'w']].values)
    # Calculate rotation change and position change
    df_cleaned[['re_roll', 're_pitch', 're_yaw']]= df_cleaned[['re_x', 're_y', 're_z', 're_w']].apply(quaternion_to_euler, axis=1)
    df_cleaned['RE_speed'] = calculate_speed(df_cleaned['re_p1'], df_cleaned['re_p2'], df_cleaned['re_p3'], df_cleaned['timestamp'], df_cleaned['re_p1'].shift(1), df_cleaned['re_p2'].shift(1), df_cleaned['re_p3'].shift(1), df_cleaned['timestamp'].shift(1))
    df_cleaned['RE_pos_change']=calculate_position_change(df_cleaned['re_p1'], df_cleaned['re_p2'], df_cleaned['re_p3'], df_cleaned['re_p1'].shift(1), df_cleaned['re_p2'].shift(1), df_cleaned['re_p3'].shift(1))


    #Pose: Head

    df_cleaned[['h_x', 'h_y', 'h_z', 'h_w']] = df_cleaned['head_dir'].apply(lambda x: pd.Series(ast.literal_eval(x)))
    df_cleaned[['h_roll', 'h_pitch', 'h_yaw']] = df_cleaned[['h_x', 'h_y', 'h_z', 'h_w']].apply(quaternion_to_euler, axis=1)
    # df_cleaned['Head_Rot_Change'] = calculate_rotation_change(df_cleaned[['h_x', 'h_y', 'h_z', 'h_w']].values, df_cleaned[['h_x', 'h_y', 'h_z', 'h_w']].shift(1).values)

    df_cleaned[['h_p1', 'h_p2', 'h_p3']] = df_cleaned['head_pos'].apply(lambda x: pd.Series(ast.literal_eval(x)))
    df_cleaned['Head_Speed'] = calculate_speed(df_cleaned['h_p1'], df_cleaned['h_p2'], df_cleaned['h_p3'],df_cleaned['timestamp'], df_cleaned['h_p1'].shift(1), df_cleaned['h_p2'].shift(1), df_cleaned['h_p3'].shift(1), df_cleaned['timestamp'].shift(1))
    df_cleaned['Head_pos_change']=calculate_position_change(df_cleaned['h_p1'], df_cleaned['h_p2'], df_cleaned['h_p3'], df_cleaned['h_p1'].shift(1), df_cleaned['h_p2'].shift(1), df_cleaned['h_p3'].shift(1))
    
    df_cleaned[['h_vp1', 'h_vp2', 'h_vp3']] = df_cleaned['head_vel'].apply(lambda x: pd.Series(ast.literal_eval(x)))
    df_cleaned['Head_Velocity_Change'] = calculate_position_change(df_cleaned['h_vp1'], df_cleaned['h_vp2'], df_cleaned['h_vp3'], df_cleaned['h_vp1'].shift(1), df_cleaned['h_vp2'].shift(1), df_cleaned['h_vp3'].shift(1))

    df_cleaned[['h_avp1', 'h_avp2', 'h_avp3']] = df_cleaned['head_angvel'].apply(lambda x: pd.Series(ast.literal_eval(x)))
    df_cleaned['Head_AngVel_Change'] = calculate_position_change(df_cleaned['h_avp1'], df_cleaned['h_avp2'], df_cleaned['h_avp3'], df_cleaned['h_avp1'].shift(1), df_cleaned['h_avp2'].shift(1), df_cleaned['h_avp3'].shift(1))

    
    #camera extractions
    
    df_cleaned['v_matrix'] = df_cleaned['v_matrix'].apply(ast.literal_eval)
    df_cleaned['camera_name'] = df_cleaned['camera_name'].apply(ast.literal_eval)
    df_cleaned['p_matrix'] = df_cleaned['p_matrix'].apply(ast.literal_eval)
    df_cleaned['object_name'] = df_cleaned['object_name'].apply(ast.literal_eval)


    cam_name=df_cleaned['camera_name'].to_list()
    timest=df_cleaned['timestamp'].to_list()
    v_matrix=df_cleaned['v_matrix'].to_list()
    p_matrix=df_cleaned['p_matrix'].to_list()

    c_roll=np.zeros(len(cam_name))
    c_pitch=np.zeros(len(cam_name))
    c_yaw=np.zeros(len(cam_name))
    c_x=np.zeros(len(cam_name))
    c_y=np.zeros(len(cam_name))
    c_z=np.zeros(len(cam_name))
    c_speed=np.zeros(len(cam_name))
    c_fov=np.zeros(len(cam_name))
    # c_fov_change=np.zeros(len(cam_name))

    for i in range(0,len(cam_name)):
        for y in range(len(cam_name[i])):
            # print(cam_name[i][y])
            if cam_name[i][y]=='CenterEyeAnchor':
                v_mat=v_matrix[i][y]
                # print(v_mat)
                c_x[i], c_y[i], c_z[i], c_yaw[i], c_pitch[i], c_roll[i]=extract_position_and_euler_angles_from_matrix(v_mat)
                c_fov[i]=p_matrix[i][y][0]
                
                if i!=0:
                    timediff=(timest[i]-timest[i-1])/1000
                    velocity=[(c_x[i]-c_x[i-1])/timediff, (c_y[i]-c_y[i-1])/timediff, (c_z[i]-c_z[i-1])/timediff]
                    c_speed[i]=np.linalg.norm(velocity)
                    # c_fov_change=(c_fov[i]-c_fov[i-1])*100000000

    # print(c_roll[0:5])
    df_cleaned['c_roll']=c_roll
    df_cleaned['c_pitch']=c_pitch
    df_cleaned['c_yaw']=c_yaw
    df_cleaned['c_x']=c_x
    df_cleaned['c_y']=c_y
    df_cleaned['c_z']=c_z
    df_cleaned['c_speed']=c_speed
    df_cleaned['c_fov']=c_fov
    # df_cleaned['c_fov_change']=c_fov_change
    df_cleaned['c_change_pitch']=df_cleaned['c_pitch']-df_cleaned['c_pitch'].shift(1)
    df_cleaned['c_change_roll']=df_cleaned['c_roll']-df_cleaned['c_roll'].shift(1)
    df_cleaned['c_change_yaw']=df_cleaned['c_yaw']-df_cleaned['c_yaw'].shift(1)
    # Apply the function to each row of the 'object_name' column
    df_cleaned['text_presence'] = df_cleaned['object_name'].apply(check_for_text)
    # Display the modified DataFrame
    # print(df)
    # print("nan_count = ", df_cleaned['video'].isna().sum())
    # Example usage
    v_paths=df_cleaned['video'].to_list()
    # print(vpaths[0])
    vpaths=[]
    ind=0

    for i in range(len(v_paths)):
        # print(video_list[video])
        if str(v_paths[i]).startswith('vid'):
            vpaths.append( df_sess_path + str(v_paths[i]) + '.jpg')
            ind=i
        else:
            # print('yes')
            # print(i)
            vpaths.append(df_sess_path + str(v_paths[ind]) + '.jpg')
    
    images = [cv2.imread(image_path) for image_path in vpaths]
    df_cleaned['change in brightness']=detect_lighting_changes(images)
    
    
    df_cleaned['diff_HE_yaw'] = df_cleaned['le_yaw'] - df_cleaned['h_yaw']
    df_cleaned['diff_HE_roll'] = df_cleaned['le_roll'] - df_cleaned['h_roll']
    df_cleaned['diff_HE_pitch'] = df_cleaned['le_pitch'] - df_cleaned['h_pitch']
    
    df['hour'] = pd.to_datetime(df['timestamp'], unit='ms').dt.tz_localize('UTC').dt.tz_convert('Asia/Shanghai').dt.hour
    
    df_cleaned.reset_index(drop=True, inplace=True)
    
    df_final=df_cleaned[['frame', 'hour','Buttons', 'IndTrig_L', 'IndTrig_R', 'HandTrig_L',
       'HandTrig_R', 'Thumb_L', 'Thumb_R', 'Thumb_L_x', 'Thumb_R_x', 'Thumb_L_y', 'Thumb_R_y', 
       'LE_speed', 'LE_pos_change','Head_Speed', 'Head_pos_change', 'Head_Velocity_Change', 'Head_AngVel_Change', 
       'c_speed',  'text_presence', 'change in brightness','diff_HE_yaw', 'diff_HE_roll', 'diff_HE_pitch' , 
       'c_change_pitch', 'c_change_roll', 'c_change_yaw', 'MS_rating']]
    
    return df_final

In [40]:
import pandas as pd
import numpy as np

def clean_buttons(buttons):
    if np.isnan(buttons):
        return 0
    buttons = int(buttons)
    buttons_bin = bin(buttons)[2:]
    button_presses = buttons_bin.count('1')
    return button_presses

def get_a_pressed(buttons):
    if np.isnan(buttons):
        return 0
    return 1 if int(buttons) & 1 else 0

def clean_triggers(trigger):
    if np.isnan(trigger):
        return 0
    return 1 if trigger != 0.0 else 0

def clean_thumbs(thumb):
    if np.isnan(thumb):
        return 0
    return 1 if thumb < 0.0 else 0

# df = pd.read_csv("shreyas.csv")

col_list = ['Buttons', 'IndTrig_L', 'IndTrig_R', 'HandTrig_L', 'HandTrig_R', 'Thumb_L', 'Thumb_R', 'Thumb_L_x', 'Thumb_R_x', 'Thumb_L_y', 'Thumb_R_y', 'LE_speed', 'LE_pos_change', 'Head_Speed', 'Head_pos_change', 'Head_Velocity_Change', 'Head_AngVel_Change', 'c_speed', 'text_presence', 'change in brightness', 'diff_HE_yaw', 'diff_HE_roll', 'diff_HE_pitch', 'c_change_pitch', 'c_change_roll', 'c_change_yaw', 'MS_rating', 'hour']
difficult_agg_list = ['Buttons', 'IndTrig_L', 'IndTrig_R', 'HandTrig_L', 'HandTrig_R', 'Thumb_L_x', 'Thumb_R_x', 'Thumb_L_y', 'Thumb_R_y']

easy_agg_list = [item for item in col_list if item not in difficult_agg_list]




def aggregate(df):
    col_list = ['Buttons', 'IndTrig_L', 'IndTrig_R', 'HandTrig_L', 'HandTrig_R', 'Thumb_L', 'Thumb_R', 'Thumb_L_x', 'Thumb_R_x', 'Thumb_L_y', 'Thumb_R_y', 'LE_speed', 'LE_pos_change', 'Head_Speed', 'Head_pos_change', 'Head_Velocity_Change', 'Head_AngVel_Change', 'c_speed', 'text_presence', 'change in brightness', 'diff_HE_yaw', 'diff_HE_roll', 'diff_HE_pitch', 'c_change_pitch', 'c_change_roll', 'c_change_yaw', 'MS_rating']
    difficult_agg_list = ['Buttons', 'IndTrig_L', 'IndTrig_R', 'HandTrig_L', 'HandTrig_R', 'Thumb_L_x', 'Thumb_R_x', 'Thumb_L_y', 'Thumb_R_y']

    easy_agg_list = [item for item in col_list if item not in difficult_agg_list]
    df= df[col_list]
    
    # Find indices of non-NaN MS_rating values
    non_nan_indices = df[df['MS_rating'].notna()].index.tolist()

    # Initialize a dictionary to hold the groups
    groups = {}

    # Calculate bucket size for each group and extract the group
    for i, idx in enumerate(non_nan_indices):
        # For the first non-NaN value
        if i == 0:
            next_idx = non_nan_indices[i + 1] if i + 1 < len(non_nan_indices) else df.index.max()
            half_gap = (next_idx - idx) // 2
            start_idx = df.index.min()
            end_idx = idx + half_gap
        # For the last non-NaN value
        elif i == len(non_nan_indices) - 1:
            prev_idx = non_nan_indices[i - 1]
            half_gap = (idx - prev_idx) // 2
            start_idx = prev_idx + half_gap
            end_idx = df.index.max()
        # For non-NaN values in between
        else:
            prev_idx = non_nan_indices[i - 1]
            next_idx = non_nan_indices[i + 1]
            half_gap_prev = (idx - prev_idx) // 2
            half_gap_next = (next_idx - idx) // 2
            start_idx = idx - half_gap_prev
            end_idx = idx + half_gap_next

        # Extract the group of rows for the current index
        groups[idx] = (start_idx, end_idx)

    # Display the groups
    # for center_frame, group in groups.items():
    #     print(f"Group centered at frame {center_frame}:")
    #     print(group, "\n")

    easy_df = df[easy_agg_list]
    agg_easy_df = None

    easy_aggregations = {
        'Thumb_L': 'sum',
        'Thumb_R': 'sum',
        'LE_speed': ['mean', 'median'],
        'LE_pos_change': ['mean', 'median', 'sum'],
        'Head_Speed': ['mean', 'median'],
        'Head_pos_change': ['mean', 'median', 'sum'],
        'Head_Velocity_Change': ['mean', 'median'],
        'Head_AngVel_Change': ['mean', 'median'],
        'c_speed': ['mean', 'median'],
        'text_presence': 'sum',
        'change in brightness': ['mean', 'median'],
        'diff_HE_yaw': ['mean', 'median', 'sum'],
        'diff_HE_roll': ['mean', 'median', 'sum'],
        'diff_HE_pitch': ['mean', 'median', 'sum'],
        'c_change_pitch': ['mean', 'median', 'sum'],
        'c_change_roll': ['mean', 'median', 'sum'],
        'c_change_yaw': ['mean', 'median', 'sum'],
        'MS_rating': 'sum',
        'hour': 'median'
    }

    difficult_df = df[difficult_agg_list]
    agg_difficult_df = None

    difficult_agg_list = ['Buttons', 'IndTrig_L', 'IndTrig_R', 'HandTrig_L', 'HandTrig_R', 'Thumb_L_x', 'Thumb_R_x', 'Thumb_L_y', 'Thumb_R_y']
    difficult_df['Buttons_cleaned'] = difficult_df['Buttons'].apply(clean_buttons)
    difficult_df['A_Pressed'] = difficult_df['Buttons'].apply(get_a_pressed)
    difficult_df.drop(columns=['Buttons'], inplace=True)
    difficult_df.rename(columns={'Buttons_cleaned': 'Buttons'}, inplace=True)

    difficult_df['IndTrig_L_cleaned'] = difficult_df['IndTrig_L'].apply(clean_triggers)
    difficult_df.drop(columns=['IndTrig_L'], inplace=True)
    difficult_df.rename(columns={'IndTrig_L_cleaned': 'IndTrig_L'}, inplace=True)
    difficult_df['IndTrig_R_cleaned'] = difficult_df['IndTrig_R'].apply(clean_triggers)
    difficult_df.drop(columns=['IndTrig_R'], inplace=True)
    difficult_df.rename(columns={'IndTrig_R_cleaned': 'IndTrig_R'}, inplace=True)
    difficult_df['HandTrig_L_cleaned'] = difficult_df['HandTrig_L'].apply(clean_triggers)
    difficult_df.drop(columns=['HandTrig_L'], inplace=True)
    difficult_df.rename(columns={'HandTrig_L_cleaned': 'HandTrig_L'}, inplace=True)
    difficult_df['HandTrig_R_cleaned'] = difficult_df['HandTrig_R'].apply(clean_triggers)
    difficult_df.drop(columns=['HandTrig_R'], inplace=True)
    difficult_df.rename(columns={'HandTrig_R_cleaned': 'HandTrig_R'}, inplace=True)

    difficult_df['Thumb_L_x_cleaned'] = difficult_df['Thumb_L_x'].apply(clean_thumbs)
    difficult_df.drop(columns=['Thumb_L_x'], inplace=True)
    difficult_df.rename(columns={'Thumb_L_x_cleaned': 'Thumb_L_x'}, inplace=True)
    difficult_df['Thumb_R_x_cleaned'] = difficult_df['Thumb_R_x'].apply(clean_thumbs)
    difficult_df.drop(columns=['Thumb_R_x'], inplace=True)
    difficult_df.rename(columns={'Thumb_R_x_cleaned': 'Thumb_R_x'}, inplace=True)
    difficult_df['Thumb_L_y_cleaned'] = difficult_df['Thumb_L_y'].apply(clean_thumbs)
    difficult_df.drop(columns=['Thumb_L_y'], inplace=True)
    difficult_df.rename(columns={'Thumb_L_y_cleaned': 'Thumb_L_y'}, inplace=True)
    difficult_df['Thumb_R_y_cleaned'] = difficult_df['Thumb_R_y'].apply(clean_thumbs)
    difficult_df.drop(columns=['Thumb_R_y'], inplace=True)
    difficult_df.rename(columns={'Thumb_R_y_cleaned': 'Thumb_R_y'}, inplace=True)

    difficult_aggregations = {
        'Buttons': 'sum',
        'A_Pressed': 'sum',
        'IndTrig_L': 'sum',
        'IndTrig_R': 'sum',
        'HandTrig_L': 'sum',
        'HandTrig_R': 'sum',
        'Thumb_L_x': 'sum',
        'Thumb_R_x': 'sum',
        'Thumb_L_y': 'sum',
        'Thumb_R_y': 'sum'
    }

    e_flag, d_flag = 0, 0

    # Aggregate values in each interval
    for center_frame, group in groups.items():
        start, end = group
        interval_values_easy = easy_df.loc[start:end]
        new_easy_row = interval_values_easy.agg(easy_aggregations)

        stacked = new_easy_row.T.stack()
        stacked_df = stacked.to_frame('value')
        stacked_df.index = ['_'.join(idx) for idx in stacked.index]
        final_e_row = stacked_df.T

        if (e_flag == 0):
            agg_easy_df = pd.DataFrame(columns=final_e_row.index)
            e_flag = 1
        agg_easy_df = pd.concat([agg_easy_df, final_e_row], axis=0, ignore_index=True)

        interval_values_difficult = difficult_df.loc[start:end]
        new_difficult_row = interval_values_difficult.agg(difficult_aggregations)
        final_d_row = new_difficult_row.to_frame().T
        if (d_flag == 0):
            agg_difficult_df = pd.DataFrame(columns=final_d_row.columns)
            d_flag = 1
        agg_difficult_df = pd.concat([agg_difficult_df, final_d_row], axis=0, ignore_index=True)

    agg_easy_df.drop(columns=['value'], inplace=True)

    # Concatenate easy and difficult aggregation dataframes
    result = pd.concat([agg_easy_df, agg_difficult_df], axis=1)

    return result

In [1]:
import warnings

# Ignore warnings
warnings.filterwarnings('ignore')

In [3]:
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import os
# import shutil
# import csv
# import math
# import json
# import ast
# import cv2
# import logging

# from clean import * 
# from aggregation import *
# # Define logger
# from logger_config import setup_logger

# # Get logger
# logger = setup_logger()


# game_abbs={'Earth_Gym': 1,
#  'Wild_Quest': 2,
#  'Roommate': 3,
#  'Waffle_Restaurant': 4,
#  'Superhero_Arena': 5,
#  'Army_Men': 6,
#  'Bobber_Bay_Fishing': 7,
#  'Citadel': 8,
#  'Mars_Miners': 9,
#  'American_Idol': 10,
#  'Kawaii_Daycare': 11,
#  'Giant_Paddle_Golf': 12,
#  'City_Parkour': 13,
#  'Wake_the_Robot': 14,
#  'The_aquarium': 15,
#  'UFO_crash_site_venue': 16,
#  'Kowloon': 17,
#  'Arena_Clash': 18,
#  'Scifi_Sandbox': 19,
#  'Super_Rumble': 20,
#  'Slash_RPG': 21,
#  'Pirate_Life': 22,
#  'Zombie': 23,
#  'Horizon_Boxing': 24,
#  'VR_Classroom': 25,
#  'Venues': 26,
#  'Metdonalds': 27,
#  '3D_Play_House': 28,
#  'Out_Of_Control': 29,
#  'Geometry_Gunners': 30,
#  'Barnyard': 31,
#  'Canyon_Runners': 32,
#  'Titanic_Simulation': 33,
#  'Creature_Feature': 34}

# cleaned_dfs = []

# def panel(df, user_id, game_id,order):
#     df.reset_index(drop=False, inplace=True)
#     df.rename(columns={'index': 'time'}, inplace=True)
#     df['user_id'] = user_id
#     df['game_id'] = game_id  
#     df['order'] = order 
#     return df

# with open('/home/dinithi/vr-motion-sickness-modelling/DataExtractionScripts/log_csvs/games_used1.json', 'r') as f:
#     games = json.load(f)

# root_dir='/data/VR_NET/folders'

# logger.info('--------------------------------aggregation starting----------------------------------------------------------------------------------')

# games={'Earth_Gym': ['5_2_Earth_Gym',
#   '10_2_Earth_Gym']}


# for game in games:
#     logger.info(f'***************{game}********************')
#     for sess in games[game]:
#         logger.info(f'*******{sess}********')
#         sess_path=os.path.join(root_dir, game, sess)
#         user_id=int(sess.split('_')[0])
#         game_id=game_abbs[game]
#         order=int(sess.split('_')[1])
#         # print(sess_path)
#         # try:
#         df_clean=clean(sess_path)
#         df_agg=aggregate(df_clean)
#         df_fin=panel(df_agg, user_id, game_id,order)
#         cleaned_dfs.append(df_fin)
#         # logger.info('successful aggregation')
#         # # except:
#         # logger.info('failed aggregation')

            

# panel_df = pd.concat(cleaned_dfs, ignore_index=True)

# panel_df.to_csv('panel_data2.csv',  index=False)

In [4]:
df_clean['hour'].value_counts()

11    4619
Name: hour, dtype: int64

In [6]:
df_clean['change in brightness']

0       0
1       0
2       0
3       0
4       0
       ..
4614    0
4615    0
4616    0
4617    0
4618    0
Name: change in brightness, Length: 4619, dtype: int64

In [4]:
panel_df['change in brightness_mean']

0      3.575182
1      3.539671
2      5.606859
3      4.198118
4      8.341409
5      7.514897
6      7.529263
7      4.550402
8      7.408330
9      8.009633
10     9.002134
11     6.059803
12    13.714350
13     1.866590
14     5.947784
15     2.685826
16     6.789496
17     6.268494
18     5.963213
19     1.837228
20     4.785284
21     9.467973
22     4.500957
23     6.442177
24     4.233822
25     4.175833
Name: change in brightness_mean, dtype: float64

In [5]:
panel_df.columns

Index(['time', 'Thumb_L_sum', 'Thumb_R_sum', 'LE_speed_mean',
       'LE_speed_median', 'LE_pos_change_sum', 'LE_pos_change_mean',
       'LE_pos_change_median', 'Head_Speed_mean', 'Head_Speed_median',
       'Head_pos_change_sum', 'Head_pos_change_mean', 'Head_pos_change_median',
       'Head_Velocity_Change_mean', 'Head_Velocity_Change_median',
       'Head_AngVel_Change_mean', 'Head_AngVel_Change_median', 'c_speed_mean',
       'c_speed_median', 'text_presence_sum', 'change in brightness_mean',
       'change in brightness_median', 'diff_HE_yaw_sum', 'diff_HE_yaw_mean',
       'diff_HE_yaw_median', 'diff_HE_roll_sum', 'diff_HE_roll_mean',
       'diff_HE_roll_median', 'diff_HE_pitch_sum', 'diff_HE_pitch_mean',
       'diff_HE_pitch_median', 'c_change_pitch_sum', 'c_change_pitch_mean',
       'c_change_pitch_median', 'c_change_roll_sum', 'c_change_roll_mean',
       'c_change_roll_median', 'c_change_yaw_sum', 'c_change_yaw_mean',
       'c_change_yaw_median', 'MS_rating_sum', 'hour_median', 'Buttons',
       'A_Pressed', 'IndTrig_L', 'IndTrig_R', 'HandTrig_L', 'HandTrig_R',
       'Thumb_L_x', 'Thumb_R_x', 'Thumb_L_y', 'Thumb_R_y', 'user_id',
       'game_id', 'order'],
      dtype='object')

In [8]:
v_paths=df_cleaned['video'].to_list()
# print(vpaths[0])
vpaths=[]
ind=0

for i in range(len(v_paths)):
    # print(video_list[video])
    if str(v_paths[i]).startswith('vid'):
        vpaths.append( df_sess_path + str(v_paths[i]) + '.jpg')
        ind=i
    else:
        # print('yes')
        # print(i)
        vpaths.append(df_sess_path + str(v_paths[ind]) + '.jpg')

images = [cv2.imread(image_path) for image_path in vpaths]
df_cleaned['change in brightness']=detect_lighting_changes(images)

NameError: name 'df_cleaned' is not defined

In [6]:
panel_df['hour_median']

0     11.0
1     11.0
2     11.0
3     11.0
4     11.0
5     11.0
6     11.0
7     11.0
8     11.0
9     11.0
10    11.0
11    11.0
12    11.0
13    15.0
14    15.0
15    15.0
16    15.0
17    15.0
18    15.0
19    15.0
20    15.0
21    15.0
22    15.0
23    15.0
24    15.0
25    15.0
Name: hour_median, dtype: float64

### aux2

In [7]:
df.columns

Index(['time', 'Thumb_L_sum', 'Thumb_R_sum', 'LE_speed_mean',
       'LE_speed_median', 'LE_pos_change_sum', 'LE_pos_change_mean',
       'LE_pos_change_median', 'Head_Speed_mean', 'Head_Speed_median',
       'Head_pos_change_sum', 'Head_pos_change_mean', 'Head_pos_change_median',
       'Head_Velocity_Change_mean', 'Head_Velocity_Change_median',
       'Head_AngVel_Change_mean', 'Head_AngVel_Change_median', 'c_speed_mean',
       'c_speed_median', 'text_presence_sum', 'change in brightness_mean',
       'change in brightness_median', 'diff_HE_yaw_sum', 'diff_HE_yaw_mean',
       'diff_HE_yaw_median', 'diff_HE_roll_sum', 'diff_HE_roll_mean',
       'diff_HE_roll_median', 'diff_HE_pitch_sum', 'diff_HE_pitch_mean',
       'diff_HE_pitch_median', 'c_change_pitch_sum', 'c_change_pitch_mean',
       'c_change_pitch_median', 'c_change_roll_sum', 'c_change_roll_mean',
       'c_change_roll_median', 'c_change_yaw_sum', 'c_change_yaw_mean',
       'c_change_yaw_median', 'MS_rating_sum', 'hour_median', 'Buttons',
       'A_Pressed', 'IndTrig_L', 'IndTrig_R', 'HandTrig_L', 'HandTrig_R',
       'Thumb_L_x', 'Thumb_R_x', 'Thumb_L_y', 'Thumb_R_y', 'user_id',
       'game_id', 'order'],
      dtype='object')

In [4]:
demo=pd.read_csv('/home/dinithi/Demographic_Horizon_Study.csv')

In [5]:
demo

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,ExternalReference,LocationLatitude,LocationLongitude,DistributionChannel,UserLanguage,Q1,Q2,Q3,Q4,Q6
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,External Data Reference,Location Latitude,Location Longitude,Distribution Channel,User Language,What is your age?,Gender,Have you ever used a VR application?,Are you familiar with VR interfaces?,Participant ID
1,"{""ImportId"":""startDate"",""timeZone"":""Pacific/Au...","{""ImportId"":""endDate"",""timeZone"":""Pacific/Auck...","{""ImportId"":""status""}","{""ImportId"":""ipAddress""}","{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}","{""ImportId"":""recordedDate"",""timeZone"":""Pacific...","{""ImportId"":""_recordId""}","{""ImportId"":""recipientLastName""}",...,"{""ImportId"":""externalDataReference""}","{""ImportId"":""locationLatitude""}","{""ImportId"":""locationLongitude""}","{""ImportId"":""distributionChannel""}","{""ImportId"":""userLanguage""}","{""ImportId"":""QID123619341_TEXT""}","{""ImportId"":""QID123619342""}","{""ImportId"":""QID123619343""}","{""ImportId"":""QID123619344""}","{""ImportId"":""QID6_TEXT""}"
2,2023-09-26 14:13:19,2023-09-26 14:13:43,IP Address,137.132.212.136,100,24,True,2023-09-26 14:13:44,R_3D1rJvTPSLf3DC0,NaN,...,NaN,1.2929,103.8547,anonymous,EN,18,Female,Once,Novice,NaN
3,2023-09-26 14:13:55,2023-09-26 14:14:09,Spam,137.132.212.136,100,14,True,2023-09-26 14:14:10,R_570TXWaAISvyTTP,NaN,...,NaN,1.2929,103.8547,anonymous,EN,18,Female,Once,Novice,NaN
4,2023-09-26 14:49:05,2023-09-26 15:50:17,IP Address,104.28.119.110,100,3672,True,2023-09-26 15:50:18,R_12A4SbKtSB5PZ9i,NaN,...,NaN,1.2929,103.8547,anonymous,EN,27,Male,Few times a month,-,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388,2023-11-29 19:11:36,2023-11-29 19:47:59,IP Address,137.132.218.137,100,2183,True,2023-11-29 19:48:00,R_24vcoK2kJm98jsl,NaN,...,NaN,1.2868,103.8503,anonymous,EN,20,Female,Not at all,-,416
389,2023-11-29 20:50:02,2023-11-29 21:14:11,IP Address,122.11.212.212,100,1448,True,2023-11-29 21:14:12,R_305M9GBxOQZGCzh,NaN,...,NaN,1.3248,103.8566,anonymous,EN,21,Male,Once,-,417
390,2023-11-29 21:14:24,2023-11-29 22:06:49,IP Address,122.11.212.212,100,3145,True,2023-11-29 22:06:50,R_YXi6hBRWbwBOTcZ,NaN,...,NaN,1.3248,103.8566,anonymous,EN,22,Female,Few times a year,-,418
391,2023-11-30 15:01:40,2023-11-30 15:02:35,IP Address,137.132.217.135,100,54,True,2023-11-30 15:02:35,R_1ghk495g048cJPX,NaN,...,NaN,1.2868,103.8503,anonymous,EN,22,Female,Few times a year,Neutral,419
392,2023-12-01 22:58:41,2023-12-01 23:01:19,IP Address,122.11.214.2,100,157,True,2023-12-01 23:01:20,R_2E9VbtIFjHLzwRc,NaN,...,NaN,1.3596,103.8637,anonymous,EN,24,Male,Few times a year,-,420

In [6]:
demodf=demo[['StartDate', 'EndDate', 'Q1', 'Q2', 'Q3', 'Q6']]
demodf=demodf[2:]
merged_df = pd.merge(panel, demo1, on='user_id', how='left')

In [7]:
demodf=demodf[2:]

In [8]:
demodf

,StartDate,EndDate,Q1,Q2,Q3,Q6
2,2023-09-26 14:13:19,2023-09-26 14:13:43,18,Female,Once,NaN
3,2023-09-26 14:13:55,2023-09-26 14:14:09,18,Female,Once,NaN
4,2023-09-26 14:49:05,2023-09-26 15:50:17,27,Male,Few times a month,NaN
5,2023-09-26 15:50:54,2023-09-26 16:24:58,18,Male,Not at all,NaN
6,2023-09-26 16:28:14,2023-09-26 19:03:09,22,Female,Once,NaN
...,...,...,...,...,...,...
388,2023-11-29 19:11:36,2023-11-29 19:47:59,20,Female,Not at all,416
389,2023-11-29 20:50:02,2023-11-29 21:14:11,21,Male,Once,417
390,2023-11-29 21:14:24,2023-11-29 22:06:49,22,Female,Few times a year,418
391,2023-11-30 15:01:40,2023-11-30 15:02:35,22,Female,Few times a year,419
392,2023-12-01 22:58:41,2023-12-01 23:01:19,24,Male,Few times a year,420

In [38]:
with open('/home/dinithi/vr-motion-sickness-modelling/DataExtractionScripts/log_csvs/games_used1.json', 'r') as f:
    games = json.load(f)

root_dir='/data/VR_NET/folders'

gamest={}

for game in games:
    # logger.info(f'***************{game}********************')
    for sess in games[game]:
        # logger.info(f'*******{sess}********')
        sess_path=os.path.join(root_dir, game, sess)
        user_id=int(sess.split('_')[0])
        # game_id=game_abbs[game]
        order=int(sess.split('_')[1])
        # # print(sess_path)
        # try:
        if order==1:
            df_sess_path_df=os.path.join(sess_path,'data_file.csv')
            df_clean=pd.read_csv(df_sess_path_df)
            timestamp= df_clean['timestamp'][0:1].to_list()[0]
            gamest[user_id]=timestamp
            
#         except:
#             # logger.info('failed aggregation')
#             print('session fialed', df_sess_path_df)

with open('gamest.json', 'w') as json_file:
    json.dump(gamest, json_file)            

# panel_df = pd.concat(cleaned_dfs, ignore_index=True)

# panel_df.to_csv('panel_data_2.csv',  index=False)

ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

In [ ]:
gamest

In [10]:
demodf

,StartDate,EndDate,Q1,Q2,Q3,Q6
2,2023-09-26 14:13:19,2023-09-26 14:13:43,18,Female,Once,NaN
3,2023-09-26 14:13:55,2023-09-26 14:14:09,18,Female,Once,NaN
4,2023-09-26 14:49:05,2023-09-26 15:50:17,27,Male,Few times a month,NaN
5,2023-09-26 15:50:54,2023-09-26 16:24:58,18,Male,Not at all,NaN
6,2023-09-26 16:28:14,2023-09-26 19:03:09,22,Female,Once,NaN
...,...,...,...,...,...,...
388,2023-11-29 19:11:36,2023-11-29 19:47:59,20,Female,Not at all,416
389,2023-11-29 20:50:02,2023-11-29 21:14:11,21,Male,Once,417
390,2023-11-29 21:14:24,2023-11-29 22:06:49,22,Female,Few times a year,418
391,2023-11-30 15:01:40,2023-11-30 15:02:35,22,Female,Few times a year,419
392,2023-12-01 22:58:41,2023-12-01 23:01:19,24,Male,Few times a year,420

In [11]:
demodf.columns

Index(['StartDate', 'EndDate', 'Q1', 'Q2', 'Q3', 'Q6'], dtype='object')

In [12]:
from datetime import datetime
import pytz

# Define the input timestamp
timestamp_str = "2023-09-26 14:13:19"

# Convert string to datetime object
timestamp = datetime.strptime(timestamp_str, "%Y-%m-%d %H:%M:%S")

# Set the timezone to GMT+8
gmt_plus_8 = pytz.timezone('Asia/Shanghai')
timestamp_gmt_plus_8 = gmt_plus_8.localize(timestamp)

# Convert to Unix epoch timestamp
unix_epoch_timestamp = int(timestamp_gmt_plus_8.timestamp())

print(unix_epoch_timestamp)

1695708799

In [13]:
timestamp = datetime.strptime(timestamp_str, "%Y-%m-%d %H:%M:%S")

# Convert datetime object to Unix epoch timestamp in milliseconds
epoch_timestamp_ms = int(timestamp.timestamp() * 1000)

print(epoch_timestamp_ms)

1695708799000

In [14]:
times=demodf['StartDate'].to_list()
age=demodf['Q1'].to_list()
gender=demodf['Q2'].to_list()
Exp=demodf['Q3'].to_list()

In [15]:
def to_epoch(timestamp_str):
    timestamp = datetime.strptime(timestamp_str, "%Y-%m-%d %H:%M:%S")
    return int(timestamp.timestamp() * 1000)

# Convert each timestamp in the list to epoch timestamp
epoch_times_ms = [to_epoch(timestamp) for timestamp in times]

# print(epoch_times_ms)

In [16]:
# epoch_times_ms

In [17]:
def timestamp_difference(timestamp1, timestamp2):
    return abs(timestamp1 - timestamp2)

age1=[]
gender1=[]
exp1=[]
user=[]
timet


for i in gamest.keys():
    tst=gamest[i]
    # print(tst)

# Find the index of the nearest timestamp
    timediff = [timestamp_difference(tst, x) for x in epoch_times_ms ]
    min_value = min(timediff)
    min_index = timediff.index(min_value)
    user.append(i)
    age1.append(age[min_index])
    gender1.append(gender[min_index])
    exp1.append(Exp[min_index])
    timet.append()
    
df1 = pd.DataFrame({'user_id': user, 'Age': age1, 'Gender': gender1, 'Exp': exp1})

NameError: name 'timet' is not defined

In [18]:
# df = pd.DataFrame({'user_id': user, 'Age': ages})

In [19]:
user2=[]
time2=[]
for i in gamest.keys():
    user2.append(i)
    time2.append(gamest[i])
    ind=np.argsort(user2)

In [20]:
ind

array([2, 0, 1])

In [21]:
df1['Gender'].value_counts()

NameError: name 'df1' is not defined

In [22]:
df1['Exp'].value_counts()

NameError: name 'df1' is not defined

In [23]:
df1['Age'].value_counts()

NameError: name 'df1' is not defined

In [24]:
df1

NameError: name 'df1' is not defined

In [25]:
demodf['timest']=epoch_times_ms

In [26]:
demodf1=demodf[[ 'Q1', 'Q2', 'Q3', 'Q6', 'timest']]

In [27]:
demodf.columns

Index(['StartDate', 'EndDate', 'Q1', 'Q2', 'Q3', 'Q6', 'timest'], dtype='object')

In [28]:
demodf1.to_csv('demo.csv')

In [29]:
gamest.keys()

dict_keys([7, 9, 6])

In [30]:
arr=[]
for i in gamest.keys():
    arr.append(i)

In [31]:
# 
panel=pd.read_csv('panel_data_2.csv')

In [32]:
panel

,time,Thumb_L_sum,Thumb_R_sum,LE_speed_mean,LE_speed_median,LE_pos_change_sum,LE_pos_change_mean,LE_pos_change_median,Head_Speed_mean,Head_Speed_median,...,IndTrig_R,HandTrig_L,HandTrig_R,Thumb_L_x,Thumb_R_x,Thumb_L_y,Thumb_R_y,user_id,game_id,order
0,0,0.000000,3.594337,0.127828,0.090655,2.316057,0.020865,0.012802,0.172464,0.125845,...,0,32,0,0,3,0,3,5,1,2
1,1,33.093972,62.157799,0.063716,0.036334,3.967072,0.013448,0.005704,0.063247,0.036310,...,12,48,15,64,43,66,40,5,1,2
2,2,46.027865,90.608110,0.068397,0.042165,3.758526,0.009813,0.006048,0.067828,0.040388,...,4,62,37,100,63,93,70,5,1,2
3,3,18.430878,5.229467,0.068757,0.038978,3.775398,0.010068,0.005633,0.069725,0.037508,...,272,71,127,14,7,11,5,5,1,2
4,4,26.719036,1.597837,0.150314,0.117524,8.961758,0.022349,0.017352,0.153218,0.125837,...,203,27,157,22,5,21,5,5,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,103.000739,94.874378,0.034958,0.021215,2.608618,0.005598,0.003259,0.031584,0.021257,...,1,22,0,171,54,168,55,147,34,1
2930,8,53.928953,36.710560,0.043327,0.026262,2.421957,0.007295,0.004128,0.044183,0.025836,...,24,10,13,98,19,118,22,147,34,1
2931,9,45.495983,42.703410,0.026860,0.021454,1.126662,0.004471,0.003622,0.027040,0.021753,...,46,2,0,95,28,109,26,147,34,1
2932,10,17.765149,10.020055,0.123650,0.077568,5.506467,0.018858,0.012262,0.124227,0.078281,...,27,112,1,41,7,31,6,147,34,1
2933,11,6.148178,0.000000,0.063157,0.033172,1.521158,0.010074,0.005324,0.063689,0.038167,...,0,4,0,8,0,4,0,147,34,1

In [30]:
# demo=pd.read_csv('demo.csv')

In [34]:
demo.columns

Index(['Unnamed: 0', 'Q1', 'Q2', 'Q3', 'Q6', 'timest'], dtype='object')

In [35]:
demo1=demo[['Q1', 'Q2', 'Q3', 'userid']]

KeyError: "['userid'] not in index"

In [36]:
demo1

NameError: name 'demo1' is not defined

In [37]:
demo1.rename(columns={'userid': 'user_id'}, inplace=True)

NameError: name 'demo1' is not defined

In [101]:
merged_df = pd.merge(panel, demo1, on='user_id', how='left')

In [114]:
merged_df

,time,Thumb_L_sum,Thumb_R_sum,LE_speed_mean,LE_speed_median,LE_pos_change_sum,LE_pos_change_mean,LE_pos_change_median,Head_Speed_mean,Head_Speed_median,...,Thumb_L_y,Thumb_R_y,user_id,game_id,order,Q1,Q2,Q3,gender,Exp
0,0,0.000000,3.594337,0.127828,0.090655,2.316057,0.020865,0.012802,0.172464,0.125845,...,0,3,5,1,2,18,Female,Once,1,1
1,1,33.093972,62.157799,0.063716,0.036334,3.967072,0.013448,0.005704,0.063247,0.036310,...,66,40,5,1,2,18,Female,Once,1,1
2,2,46.027865,90.608110,0.068397,0.042165,3.758526,0.009813,0.006048,0.067828,0.040388,...,93,70,5,1,2,18,Female,Once,1,1
3,3,18.430878,5.229467,0.068757,0.038978,3.775398,0.010068,0.005633,0.069725,0.037508,...,11,5,5,1,2,18,Female,Once,1,1
4,4,26.719036,1.597837,0.150314,0.117524,8.961758,0.022349,0.017352,0.153218,0.125837,...,21,5,5,1,2,18,Female,Once,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,103.000739,94.874378,0.034958,0.021215,2.608618,0.005598,0.003259,0.031584,0.021257,...,168,55,147,34,1,22,Female,Few times a year,1,1
2930,8,53.928953,36.710560,0.043327,0.026262,2.421957,0.007295,0.004128,0.044183,0.025836,...,118,22,147,34,1,22,Female,Few times a year,1,1
2931,9,45.495983,42.703410,0.026860,0.021454,1.126662,0.004471,0.003622,0.027040,0.021753,...,109,26,147,34,1,22,Female,Few times a year,1,1
2932,10,17.765149,10.020055,0.123650,0.077568,5.506467,0.018858,0.012262,0.124227,0.078281,...,31,6,147,34,1,22,Female,Few times a year,1,1
2933,11,6.148178,0.000000,0.063157,0.033172,1.521158,0.010074,0.005324,0.063689,0.038167,...,4,0,147,34,1,22,Female,Few times a year,1,1

In [109]:
df=merged_df
df['gender'] = df['Q2'].apply(lambda x: 1 if x == 'Female' else 0)

In [111]:
df['Exp'] = df['Q3'].apply(lambda x: 0 if x == 'Not at all' else 1)

In [113]:
df['gender'].value_counts()

0    1600
1    1334
Name: gender, dtype: int64

In [ ]:
df.columns

Index(['time', 'Thumb_L_sum', 'Thumb_R_sum', 'LE_speed_mean',
       'LE_speed_median', 'LE_pos_change_sum', 'LE_pos_change_mean',
       'LE_pos_change_median', 'Head_Speed_mean', 'Head_Speed_median',
       'Head_pos_change_sum', 'Head_pos_change_mean', 'Head_pos_change_median',
       'Head_Velocity_Change_mean', 'Head_Velocity_Change_median',
       'Head_AngVel_Change_mean', 'Head_AngVel_Change_median', 'c_speed_mean',
       'c_speed_median', 'text_presence_sum', 'change in brightness_mean',
       'change in brightness_median', 'diff_HE_yaw_sum', 'diff_HE_yaw_mean',
       'diff_HE_yaw_median', 'diff_HE_roll_sum', 'diff_HE_roll_mean',
       'diff_HE_roll_median', 'diff_HE_pitch_sum', 'diff_HE_pitch_mean',
       'diff_HE_pitch_median', 'c_change_pitch_sum', 'c_change_pitch_mean',
       'c_change_pitch_median', 'c_change_roll_sum', 'c_change_roll_mean',
       'c_change_roll_median', 'c_change_yaw_sum', 'c_change_yaw_mean',
       'c_change_yaw_median', 'MS_rating_sum', 'hour_median', 'Buttons',
       'A_Pressed', 'IndTrig_L', 'IndTrig_R', 'HandTrig_L', 'HandTrig_R',
       'Thumb_L_x', 'Thumb_R_x', 'Thumb_L_y', 'Thumb_R_y', 'user_id',
       'game_id', 'order', 'Intensity'],
      dtype='object')

In [26]:
columns= ['time', 'MS_rating_sum', 'Thumb_L_sum', 'Thumb_R_sum', 'LE_speed_median', 'Head_Speed_median', 
          'diff_HE_yaw_median', 'diff_HE_roll_median', 'diff_HE_pitch_median', 'IndTrig_L', 'IndTrig_R',
          'c_change_pitch_median', 'c_change_roll_median' , 'c_change_yaw_median', 'c_speed_median', 'text_presence_sum', 
          'change in brightness_median', 'Buttons', 'A_Pressed', 'user_id',
           'game_id','order','Intensity']
          # 'gender', 'Exp','hour_median']

In [27]:
df.rename(columns={'old_name1': 'new_name1', 'old_name2': 'new_name2'}, inplace=True)

In [28]:
df1=df[columns]

In [29]:
df1

,time,MS_rating_sum,Thumb_L_sum,Thumb_R_sum,LE_speed_median,Head_Speed_median,diff_HE_yaw_median,diff_HE_roll_median,diff_HE_pitch_median,IndTrig_L,...,c_change_yaw_median,c_speed_median,text_presence_sum,change in brightness_median,Buttons,A_Pressed,user_id,game_id,order,Intensity
0,0,1.0,0.000000,3.594337,0.090655,0.125845,0.023973,0.151847,0.103009,0,...,0.018378,0.412177,0.0,0.711018,0,0,5,1,2,M
1,1,1.0,33.093972,62.157799,0.036334,0.036310,0.015407,0.139587,0.073105,8,...,0.008993,3.560106,170.0,0.802711,10,10,5,1,2,M
2,2,1.0,46.027865,90.608110,0.042165,0.040388,0.021860,0.111357,0.075548,0,...,0.017779,6.047342,374.0,0.556988,6,6,5,1,2,M
3,3,1.0,18.430878,5.229467,0.038978,0.037508,0.045567,0.123780,0.045428,23,...,0.009544,3.755367,338.0,0.597293,8,0,5,1,2,M
4,4,1.0,26.719036,1.597837,0.117524,0.125837,0.038202,0.132651,0.063008,18,...,0.047270,12.833862,345.0,1.991390,0,0,5,1,2,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,2.0,103.000739,94.874378,0.021215,0.021257,0.008972,0.119471,0.088997,27,...,0.008647,3.665734,466.0,0.303524,5,0,147,34,1,M
2930,8,5.0,53.928953,36.710560,0.026262,0.025836,0.024659,0.102049,0.110346,18,...,0.022219,4.673834,332.0,0.477790,8,1,147,34,1,M
2931,9,4.0,45.495983,42.703410,0.021454,0.021753,0.005350,0.065958,0.082692,0,...,0.008727,4.557301,252.0,0.218671,3,2,147,34,1,M
2932,10,3.0,17.765149,10.020055,0.077568,0.078281,0.019715,0.129249,0.100203,0,...,0.023224,6.611006,292.0,0.601054,1,0,147,34,1,M
2933,11,5.0,6.148178,0.000000,0.033172,0.038167,0.031997,0.157557,0.156572,0,...,0.012509,3.422751,151.0,0.388025,0,0,147,34,1,M

In [30]:
for i in df1.columns:
    print(i)

time
MS_rating_sum
Thumb_L_sum
Thumb_R_sum
LE_speed_median
Head_Speed_median
diff_HE_yaw_median
diff_HE_roll_median
diff_HE_pitch_median
IndTrig_L
IndTrig_R
c_change_pitch_median
c_change_roll_median
c_change_yaw_median
c_speed_median
text_presence_sum
change in brightness_median
Buttons
A_Pressed
user_id
game_id
order
Intensity

In [31]:
col_names={'MS_rating_sum' : 'MS_rating',
'Thumb_L_sum' : 'Thumbstick_L',
'Thumb_R_sum' : 'Thumbstick_R',
'LE_speed_median' : 'Eye_Speed',
'Head_Speed_median' : 'Head_Speed',
'diff_HE_yaw_median' : 'diff_Head_Eye_yaw',
'diff_HE_roll_median' : 'diff_Head_Eye_roll',
'diff_HE_pitch_median' : 'diff_Head_Eye_pitch',
'IndTrig_L' : 'Index_Trig_L',
'IndTrig_R' : 'Index_Trig_R',
'c_change_pitch_median' : 'camera_pitch',
'c_change_roll_median' : 'camera_roll',
'c_change_yaw_median' : 'camera_yaw',
'c_speed_median' : 'camera speed',
'text_presence_sum' : 'text_presence',
'change in brightness_median' : 'brightness_change',
'Buttons' : 'buttons',
'A_Pressed' : 'jumping',
'hour_median' : 'hour'}

In [32]:
df1.rename(columns=col_names, inplace=True)

In [33]:
df1

,time,MS_rating,Thumbstick_L,Thumbstick_R,Eye_Speed,Head_Speed,diff_Head_Eye_yaw,diff_Head_Eye_roll,diff_Head_Eye_pitch,Index_Trig_L,...,camera_yaw,camera speed,text_presence,brightness_change,buttons,jumping,user_id,game_id,order,Intensity
0,0,1.0,0.000000,3.594337,0.090655,0.125845,0.023973,0.151847,0.103009,0,...,0.018378,0.412177,0.0,0.711018,0,0,5,1,2,M
1,1,1.0,33.093972,62.157799,0.036334,0.036310,0.015407,0.139587,0.073105,8,...,0.008993,3.560106,170.0,0.802711,10,10,5,1,2,M
2,2,1.0,46.027865,90.608110,0.042165,0.040388,0.021860,0.111357,0.075548,0,...,0.017779,6.047342,374.0,0.556988,6,6,5,1,2,M
3,3,1.0,18.430878,5.229467,0.038978,0.037508,0.045567,0.123780,0.045428,23,...,0.009544,3.755367,338.0,0.597293,8,0,5,1,2,M
4,4,1.0,26.719036,1.597837,0.117524,0.125837,0.038202,0.132651,0.063008,18,...,0.047270,12.833862,345.0,1.991390,0,0,5,1,2,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,2.0,103.000739,94.874378,0.021215,0.021257,0.008972,0.119471,0.088997,27,...,0.008647,3.665734,466.0,0.303524,5,0,147,34,1,M
2930,8,5.0,53.928953,36.710560,0.026262,0.025836,0.024659,0.102049,0.110346,18,...,0.022219,4.673834,332.0,0.477790,8,1,147,34,1,M
2931,9,4.0,45.495983,42.703410,0.021454,0.021753,0.005350,0.065958,0.082692,0,...,0.008727,4.557301,252.0,0.218671,3,2,147,34,1,M
2932,10,3.0,17.765149,10.020055,0.077568,0.078281,0.019715,0.129249,0.100203,0,...,0.023224,6.611006,292.0,0.601054,1,0,147,34,1,M
2933,11,5.0,6.148178,0.000000,0.033172,0.038167,0.031997,0.157557,0.156572,0,...,0.012509,3.422751,151.0,0.388025,0,0,147,34,1,M

In [130]:
df1.to_csv('panel_data.csv', index=False)

In [131]:
df=df1

In [133]:
# Group by User_ID and calculate the sum of handtri_L and handtri_R
sum_by_user = df.groupby('user_id').agg({'Index_Trig_L': 'sum', 'Index_Trig_R': 'sum'})

# Create a new column indicating whether handtri_R is higher than handtri_L
sum_by_user['Right_handed'] = (sum_by_user['Index_Trig_R'] > sum_by_user['Index_Trig_L']).astype(int)

In [134]:
df = pd.merge(df, sum_by_user['Right_handed'], left_on='user_id', right_index=True, how='left')

In [135]:
df

,time,MS_rating,Thumbstick_L,Thumbstick_Y,Eye_Speed,Head_Speed,diff_Head_Eye_yaw,diff_Head_Eye_roll,diff_Head_Eye_mean,Index_Trig_L,...,brightness_change,buttons,Jumping,user_id,game_id,order,gender,Exp,hour,Right_handed
0,0,1.0,0,3,0.090655,0.100112,0.006959,0.027844,-0.123867,0,...,3.575182,0,0,5,1,2,1,1,11.0,1
1,1,1.0,64,40,0.036334,0.026943,-0.002852,0.057525,-0.011762,8,...,3.539671,10,10,5,1,2,1,1,11.0,1
2,2,1.0,100,70,0.042165,0.027152,-0.000494,0.002223,-0.010256,0,...,5.606859,6,6,5,1,2,1,1,11.0,1
3,3,1.0,14,5,0.038978,0.024813,-0.014454,0.003437,0.041308,23,...,4.198118,8,0,5,1,2,1,1,11.0,1
4,4,1.0,22,5,0.117524,0.102146,0.004757,-0.092486,-0.028045,18,...,8.341409,0,0,5,1,2,1,1,11.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,2.0,171,55,0.021215,0.012751,-0.002803,-0.140433,-0.033695,27,...,2.331750,5,0,147,34,1,1,1,17.0,1
2930,8,5.0,98,22,0.026262,0.019029,0.002527,-0.114485,-0.035175,18,...,3.597338,8,1,147,34,1,1,1,17.0,1
2931,9,4.0,95,26,0.021454,0.013011,-0.002140,-0.068527,-0.079928,0,...,2.057278,3,2,147,34,1,1,1,17.0,1
2932,10,3.0,41,6,0.077568,0.043275,-0.001054,-0.075218,-0.048384,0,...,1.317426,1,0,147,34,1,1,1,17.0,1
2933,11,5.0,8,0,0.033172,0.022219,-0.022093,-0.192634,-0.112093,0,...,2.934065,0,0,147,34,1,1,1,17.0,1

In [136]:
df['Right_handed'].value_counts()

1    2486
0     448
Name: Right_handed, dtype: int64

In [47]:
df=df_encoded

In [49]:
df2['panel_id'] = df2['game_id'] * 1000 + df2['user_id']

In [26]:
df['panel_id'].value_counts()

31165    14
1005     13
26082    13
22108    13
22112    13
         ..
25095     7
24117     7
28085     7
2006      6
31163     6
Name: panel_id, Length: 230, dtype: int64

In [27]:
# Assuming df is your DataFrame
value_counts = df['panel_id'].value_counts()

# Filter values with less than 5 occurrences
less_than_10 = value_counts[value_counts >13]

print(less_than_10)

31165    14
Name: panel_id, dtype: int64

In [28]:
# Assuming df is your DataFrame
value_counts = df['panel_id'].value_counts()

# Filter values with less than 5 occurrences
to_remove = value_counts[value_counts >13].index

# Remove rows with panel_id occurrences less than 5
df = df[~df['panel_id'].isin(to_remove)]

In [29]:
df

,time,Thumb_L_sum,Thumb_R_sum,LE_speed_mean,LE_speed_median,LE_pos_change_sum,LE_pos_change_mean,LE_pos_change_median,Head_Speed_mean,Head_Speed_median,...,HandTrig_R,Thumb_L_x,Thumb_R_x,Thumb_L_y,Thumb_R_y,user_id,game_id,order,Intensity,panel_id
0,0,0.000000,3.594337,0.127828,0.090655,2.316057,0.020865,0.012802,0.172464,0.125845,...,0,0,3,0,3,5,1,2,M,1005
1,1,33.093972,62.157799,0.063716,0.036334,3.967072,0.013448,0.005704,0.063247,0.036310,...,15,64,43,66,40,5,1,2,M,1005
2,2,46.027865,90.608110,0.068397,0.042165,3.758526,0.009813,0.006048,0.067828,0.040388,...,37,100,63,93,70,5,1,2,M,1005
3,3,18.430878,5.229467,0.068757,0.038978,3.775398,0.010068,0.005633,0.069725,0.037508,...,127,14,7,11,5,5,1,2,M,1005
4,4,26.719036,1.597837,0.150314,0.117524,8.961758,0.022349,0.017352,0.153218,0.125837,...,157,22,5,21,5,5,1,2,M,1005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,103.000739,94.874378,0.034958,0.021215,2.608618,0.005598,0.003259,0.031584,0.021257,...,0,171,54,168,55,147,34,1,M,34147
2930,8,53.928953,36.710560,0.043327,0.026262,2.421957,0.007295,0.004128,0.044183,0.025836,...,13,98,19,118,22,147,34,1,M,34147
2931,9,45.495983,42.703410,0.026860,0.021454,1.126662,0.004471,0.003622,0.027040,0.021753,...,0,95,28,109,26,147,34,1,M,34147
2932,10,17.765149,10.020055,0.123650,0.077568,5.506467,0.018858,0.012262,0.124227,0.078281,...,1,41,7,31,6,147,34,1,M,34147
2933,11,6.148178,0.000000,0.063157,0.033172,1.521158,0.010074,0.005324,0.063689,0.038167,...,0,8,0,4,0,147,34,1,M,34147

In [151]:
df['panel_id'].value_counts()

31165    14
1005     13
26082    13
22108    13
22112    13
         ..
25095     7
24117     7
28085     7
2006      6
31163     6
Name: panel_id, Length: 230, dtype: int64

In [152]:
df['game_id'].value_counts()

4     142
21    139
22    128
3     124
31    124
24    124
11    116
32    116
12    115
30    111
23    111
13    102
29    102
34    102
6      91
9      87
7      85
33     78
10     77
2      71
25     71
27     70
15     65
1      64
26     61
28     54
20     52
17     52
8      52
14     51
19     50
18     39
16     36
5      26
Name: game_id, dtype: int64

In [153]:
df['user_id'].value_counts()

5      26
120    26
152    26
101    26
155    26
       ..
29     12
131    11
148    11
6       6
163     6
Name: user_id, Length: 128, dtype: int64

In [154]:
len(df['game_id'].value_counts())

34

In [155]:
df

,time,MS_rating,Thumbstick_L,Thumbstick_Y,Eye_Speed,Head_Speed,diff_Head_Eye_yaw,diff_Head_Eye_roll,diff_Head_Eye_mean,Index_Trig_L,...,buttons,Jumping,user_id,game_id,order,gender,Exp,hour,Right_handed,panel_id
0,0,1.0,0,3,0.090655,0.100112,0.006959,0.027844,-0.123867,0,...,0,0,5,1,2,1,1,11.0,1,1005
1,1,1.0,64,40,0.036334,0.026943,-0.002852,0.057525,-0.011762,8,...,10,10,5,1,2,1,1,11.0,1,1005
2,2,1.0,100,70,0.042165,0.027152,-0.000494,0.002223,-0.010256,0,...,6,6,5,1,2,1,1,11.0,1,1005
3,3,1.0,14,5,0.038978,0.024813,-0.014454,0.003437,0.041308,23,...,8,0,5,1,2,1,1,11.0,1,1005
4,4,1.0,22,5,0.117524,0.102146,0.004757,-0.092486,-0.028045,18,...,0,0,5,1,2,1,1,11.0,1,1005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,2.0,171,55,0.021215,0.012751,-0.002803,-0.140433,-0.033695,27,...,5,0,147,34,1,1,1,17.0,1,34147
2930,8,5.0,98,22,0.026262,0.019029,0.002527,-0.114485,-0.035175,18,...,8,1,147,34,1,1,1,17.0,1,34147
2931,9,4.0,95,26,0.021454,0.013011,-0.002140,-0.068527,-0.079928,0,...,3,2,147,34,1,1,1,17.0,1,34147
2932,10,3.0,41,6,0.077568,0.043275,-0.001054,-0.075218,-0.048384,0,...,1,0,147,34,1,1,1,17.0,1,34147
2933,11,5.0,8,0,0.033172,0.022219,-0.022093,-0.192634,-0.112093,0,...,0,0,147,34,1,1,1,17.0,1,34147

In [156]:
df.to_csv('panel_data.csv', index=False)

In [157]:
for i in df.columns:
    print (i, end= ' ' )

time MS_rating Thumbstick_L Thumbstick_Y Eye_Speed Head_Speed diff_Head_Eye_yaw diff_Head_Eye_roll diff_Head_Eye_mean Index_Trig_L Index_Trig_R camera_pitch camera_roll camera_yaw camera speed text_presence brightness_change buttons Jumping user_id game_id order gender Exp hour Right_handed panel_id

In [3]:
df=pd.read_csv("panel_data.csv")

In [4]:
df

,time,MS_rating,Thumbstick_L,Thumbstick_Y,Eye_Speed,Head_Speed,diff_Head_Eye_yaw,diff_Head_Eye_roll,diff_Head_Eye_mean,Index_Trig_L,...,buttons,Jumping,user_id,game_id,order,gender,Exp,hour,Right_handed,panel_id
0,0,1.0,0,3,0.090655,0.100112,0.006959,0.027844,-0.123867,0,...,0,0,5,1,2,1,1,11.0,1,1005
1,1,1.0,64,40,0.036334,0.026943,-0.002852,0.057525,-0.011762,8,...,10,10,5,1,2,1,1,11.0,1,1005
2,2,1.0,100,70,0.042165,0.027152,-0.000494,0.002223,-0.010256,0,...,6,6,5,1,2,1,1,11.0,1,1005
3,3,1.0,14,5,0.038978,0.024813,-0.014454,0.003437,0.041308,23,...,8,0,5,1,2,1,1,11.0,1,1005
4,4,1.0,22,5,0.117524,0.102146,0.004757,-0.092486,-0.028045,18,...,0,0,5,1,2,1,1,11.0,1,1005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2883,7,2.0,171,55,0.021215,0.012751,-0.002803,-0.140433,-0.033695,27,...,5,0,147,34,1,1,1,17.0,1,34147
2884,8,5.0,98,22,0.026262,0.019029,0.002527,-0.114485,-0.035175,18,...,8,1,147,34,1,1,1,17.0,1,34147
2885,9,4.0,95,26,0.021454,0.013011,-0.002140,-0.068527,-0.079928,0,...,3,2,147,34,1,1,1,17.0,1,34147
2886,10,3.0,41,6,0.077568,0.043275,-0.001054,-0.075218,-0.048384,0,...,1,0,147,34,1,1,1,17.0,1,34147
2887,11,5.0,8,0,0.033172,0.022219,-0.022093,-0.192634,-0.112093,0,...,0,0,147,34,1,1,1,17.0,1,34147

In [5]:
game_abbs={'Earth_Gym': 1,
 'Wild_Quest': 2,
 'Roommate': 3,
 'Waffle_Restaurant': 4,
 'Superhero_Arena': 5,
 'Army_Men': 6,
 'Bobber_Bay_Fishing': 7,
 'Citadel': 8,
 'Mars_Miners': 9,
 'American_Idol': 10,
 'Kawaii_Daycare': 11,
 'Giant_Paddle_Golf': 12,
 'City_Parkour': 13,
 'Wake_the_Robot': 14,
 'The_aquarium': 15,
 'UFO_crash_site_venue': 16,
 'Kowloon': 17,
 'Arena_Clash': 18,
 'Scifi_Sandbox': 19,
 'Super_Rumble': 20,
 'Slash_RPG': 21,
 'Pirate_Life': 22,
 'Zombie': 23,
 'Horizon_Boxing': 24,
 'VR_Classroom': 25,
 'Venues': 26,
 'Metdonalds': 27,
 '3D_Play_House': 28,
 'Out_Of_Control': 29,
 'Geometry_Gunners': 30,
 'Barnyard': 31,
 'Canyon_Runners': 32,
 'Titanic_Simulation': 33,
 'Creature_Feature': 34}

In [6]:
int=pd.read_csv("/home/dinithi/game_intensity.csv")

In [7]:
int

                     Game Intensity
0                  Barbie         C
1   Escape_Puzzle_Mansion         C
2              Spy_School         I
3            Octopus_Bash         M
4           Circle_Kawaii         C
..                    ...       ...
77         Jail_Simulator         C
78            Pirate_Life         C
79        Superhero_Arena         M
80         Halloween_Wars         C
81   Man_of_Moon_Mountain         C

[82 rows x 2 columns]

In [16]:
game_intensity_dict = int.set_index('Game')['Intensity'].to_dict()

# Convert dictionary to JSON
# json_data = json.dumps(game_intensity_dict)

In [15]:
game_intensity_dict["Barbie"]

'C'

In [29]:
dic2={}
for i in game_abbs.keys():
    dic2[game_abbs[i]]=game_intensity_dict[i]

In [31]:
# dic2

In [32]:
intensity_df = pd.DataFrame(list(dic2.items()), columns=['game_id', 'Intensity'])

In [33]:
df['game_id']

0        1
1        1
2        1
3        1
4        1
        ..
2883    34
2884    34
2885    34
2886    34
2887    34
Name: game_id, Length: 2888, dtype: int64

In [34]:
# intensity_df
merged_df = pd.merge(df, intensity_df, on='game_id', how='left')

In [23]:
print("Data type of 'game_id' column in df:", df['game_id'].dtype)
print("Data type of 'game_id' column in intensity_df:", intensity_df['game_id'].dtype)

Data type of 'game_id' column in df: int64
Data type of 'game_id' column in intensity_df: object

In [27]:
intensity_df['game_id'].to_list()

['Barbie',
 'Escape_Puzzle_Mansion',
 'Spy_School',
 'Octopus_Bash',
 'Circle_Kawaii',
 'Delivery_Dash',
 'New_Olympus',
 'Junior_Chef',
 'Puddles_Theme_Park',
 'Land_Beyond',
 'Red_Dead',
 'Metdonalds',
 'Metablocks_Adventure',
 'Kawaii_Daycare',
 'Venues',
 'Mech_Playground',
 'Mars_Miners',
 'Puddles_Water_Park',
 'Kawaii_Playroom',
 'Roommate',
 'Walking_Dead',
 'Barnyard',
 'Flight_Squad',
 'The_aquarium',
 'Kawaii_Fire_Station',
 'Arena_Clash',
 'Wood_Warehouse',
 'Frisbee_Golf',
 'Wake_the_Robot',
 'VR_Bank',
 'NBA_Arena',
 'VR_Classroom',
 'Born_With_Power',
 'Horizon_Boxing',
 'Slash',
 'Bonnie_Revenge',
 'Kowloon',
 'Out_Of_Control',
 'Titanic_Simulation',
 'Earth_Gym',
 'Retro_Zombie',
 'Super_Rumble',
 'Water_Battling',
 'Kawaii_House',
 'Fun_House',
 'Giant_Paddle_Golf',
 'Creature_Feature',
 'Mega_Tasty_BBQ',
 'Wild_Quest',
 'UFO_crash_site_venue',
 'Zombie',
 'Kawaii_Urgent_Care',
 'Western_Skies_RPG',
 'Airplane_Obstacle',
 'American_Idol',
 'Army_Men',
 'Fight_the_Night',
 'Canyon_Runners',
 'MB_Deja_Vu',
 'Bobber_Bay_Fishing',
 'Live_Sandbox',
 '98_Escapes',
 'HoverTag',
 'Citadel',
 'City_Parkour',
 'Meta_Pizza_Hut_Classic',
 'Wizard_Sandbox',
 '3D_Play_House',
 'Scifi_Sandbox',
 'Cartoon_Wars',
 'Zoo_Chef_Challenge',
 'Kawaii_Police_Station',
 'Waffle_Restaurant',
 'Breakneck_Canyon',
 'Slash_RPG',
 'Sky_High_Trampoline_Park',
 'Geometry_Gunners',
 'Jail_Simulator',
 'Pirate_Life',
 'Superhero_Arena',
 'Halloween_Wars',
 'Man_of_Moon_Mountain']

In [40]:
merged_df

,time,MS_rating,Thumbstick_L,Thumbstick_Y,Eye_Speed,Head_Speed,diff_Head_Eye_yaw,diff_Head_Eye_roll,diff_Head_Eye_mean,Index_Trig_L,...,Jumping,user_id,game_id,order,gender,Exp,hour,Right_handed,panel_id,Intensity
0,0,1.0,0,3,0.090655,0.100112,0.006959,0.027844,-0.123867,0,...,0,5,1,2,1,1,11.0,1,1005,M
1,1,1.0,64,40,0.036334,0.026943,-0.002852,0.057525,-0.011762,8,...,10,5,1,2,1,1,11.0,1,1005,M
2,2,1.0,100,70,0.042165,0.027152,-0.000494,0.002223,-0.010256,0,...,6,5,1,2,1,1,11.0,1,1005,M
3,3,1.0,14,5,0.038978,0.024813,-0.014454,0.003437,0.041308,23,...,0,5,1,2,1,1,11.0,1,1005,M
4,4,1.0,22,5,0.117524,0.102146,0.004757,-0.092486,-0.028045,18,...,0,5,1,2,1,1,11.0,1,1005,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2883,7,2.0,171,55,0.021215,0.012751,-0.002803,-0.140433,-0.033695,27,...,0,147,34,1,1,1,17.0,1,34147,M
2884,8,5.0,98,22,0.026262,0.019029,0.002527,-0.114485,-0.035175,18,...,1,147,34,1,1,1,17.0,1,34147,M
2885,9,4.0,95,26,0.021454,0.013011,-0.002140,-0.068527,-0.079928,0,...,2,147,34,1,1,1,17.0,1,34147,M
2886,10,3.0,41,6,0.077568,0.043275,-0.001054,-0.075218,-0.048384,0,...,0,147,34,1,1,1,17.0,1,34147,M
2887,11,5.0,8,0,0.033172,0.022219,-0.022093,-0.192634,-0.112093,0,...,0,147,34,1,1,1,17.0,1,34147,M

In [34]:
merged_df=df1

In [35]:
one_hot_encoded = pd.get_dummies(merged_df['Intensity'])

In [36]:
one_hot_encoded

      C  I  M
0     0  0  1
1     0  0  1
2     0  0  1
3     0  0  1
4     0  0  1
...  .. .. ..
2929  0  0  1
2930  0  0  1
2931  0  0  1
2932  0  0  1
2933  0  0  1

[2934 rows x 3 columns]

In [42]:
df_encoded = pd.concat([df1, one_hot_encoded], axis=1)

In [43]:
df_encoded

,time,MS_rating,Thumbstick_L,Thumbstick_R,Eye_Speed,Head_Speed,diff_Head_Eye_yaw,diff_Head_Eye_roll,diff_Head_Eye_pitch,Index_Trig_L,...,brightness_change,buttons,jumping,user_id,game_id,order,Intensity,C,I,M
0,0,1.0,0.000000,3.594337,0.090655,0.125845,0.023973,0.151847,0.103009,0,...,0.711018,0,0,5,1,2,M,0,0,1
1,1,1.0,33.093972,62.157799,0.036334,0.036310,0.015407,0.139587,0.073105,8,...,0.802711,10,10,5,1,2,M,0,0,1
2,2,1.0,46.027865,90.608110,0.042165,0.040388,0.021860,0.111357,0.075548,0,...,0.556988,6,6,5,1,2,M,0,0,1
3,3,1.0,18.430878,5.229467,0.038978,0.037508,0.045567,0.123780,0.045428,23,...,0.597293,8,0,5,1,2,M,0,0,1
4,4,1.0,26.719036,1.597837,0.117524,0.125837,0.038202,0.132651,0.063008,18,...,1.991390,0,0,5,1,2,M,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,2.0,103.000739,94.874378,0.021215,0.021257,0.008972,0.119471,0.088997,27,...,0.303524,5,0,147,34,1,M,0,0,1
2930,8,5.0,53.928953,36.710560,0.026262,0.025836,0.024659,0.102049,0.110346,18,...,0.477790,8,1,147,34,1,M,0,0,1
2931,9,4.0,45.495983,42.703410,0.021454,0.021753,0.005350,0.065958,0.082692,0,...,0.218671,3,2,147,34,1,M,0,0,1
2932,10,3.0,17.765149,10.020055,0.077568,0.078281,0.019715,0.129249,0.100203,0,...,0.601054,1,0,147,34,1,M,0,0,1
2933,11,5.0,6.148178,0.000000,0.033172,0.038167,0.031997,0.157557,0.156572,0,...,0.388025,0,0,147,34,1,M,0,0,1

In [44]:
df_encoded['C'].value_counts()

1    1707
0    1227
Name: C, dtype: int64

In [45]:
df_encoded.drop(columns=['Intensity'], inplace=True)

In [46]:
df_encoded.to_csv("panel_data_0.csv")

## Analysis 1

In [1]:
5*60*60*1000

18000000

In [73]:
df.columns

Index(['time', 'MS_rating', 'Thumbstick_L', 'Thumbstick_R', 'Eye_Speed',
       'Head_Speed', 'diff_Head_Eye_yaw', 'diff_Head_Eye_roll',
       'diff_Head_Eye_mean', 'Index_Trig_L', 'Index_Trig_R', 'camera_pitch',
       'camera_roll', 'camera_yaw', 'camera speed', 'text_presence',
       'brightness_change', 'buttons', 'jumping', 'user_id', 'game_id',
       'order', 'C', 'I', 'M', 'panel_id'],
      dtype='object')

In [6]:
col_names={'MS_rating_sum' : 'MS_rating',
'Thumb_L_sum' : 'Thumbstick_L',
'Thumb_R_sum' : 'Thumbstick_R',
'LE_speed_median' : 'Eye_Speed',
'Head_Speed_median' : 'Head_Speed',
'diff_HE_yaw_median' : 'diff_Head_Eye_yaw',
'diff_HE_roll_median' : 'diff_Head_Eye_roll',
'diff_HE_pitch_median' : 'diff_Head_Eye_mean',
'IndTrig_L' : 'Index_Trig_L',
'IndTrig_R' : 'Index_Trig_R',
'c_change_pitch_median' : 'camera_pitch',
'c_change_roll_median' : 'camera_roll',
'c_change_yaw_median' : 'camera_yaw',
'c_speed_median' : 'camera speed',
'text_presence_sum' : 'text_presence',
'change in brightness_median' : 'brightness_change',
'Buttons' : 'Buttons',
'A_Pressed' : 'Jumping',
'hour_median' : 'hour'}

In [8]:
df2=pd.read_csv('panel_data.csv')

In [70]:
df2=df

In [71]:
df2

,time,MS_rating,Thumbstick_L,Thumbstick_R,Eye_Speed,Head_Speed,diff_Head_Eye_yaw,diff_Head_Eye_roll,diff_Head_Eye_pitch,Index_Trig_L,...,brightness_change,buttons,jumping,user_id,game_id,order,C,I,M,panel_id
0,0,1.0,0.000000,3.594337,0.090655,0.125845,0.023973,0.151847,0.103009,0,...,0.711018,0,0,5,1,2,0,0,1,1005
1,1,1.0,33.093972,62.157799,0.036334,0.036310,0.015407,0.139587,0.073105,8,...,0.802711,10,10,5,1,2,0,0,1,1005
2,2,1.0,46.027865,90.608110,0.042165,0.040388,0.021860,0.111357,0.075548,0,...,0.556988,6,6,5,1,2,0,0,1,1005
3,3,1.0,18.430878,5.229467,0.038978,0.037508,0.045567,0.123780,0.045428,23,...,0.597293,8,0,5,1,2,0,0,1,1005
4,4,1.0,26.719036,1.597837,0.117524,0.125837,0.038202,0.132651,0.063008,18,...,1.991390,0,0,5,1,2,0,0,1,1005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,2.0,103.000739,94.874378,0.021215,0.021257,0.008972,0.119471,0.088997,27,...,0.303524,5,0,147,34,1,0,0,1,34147
2930,8,5.0,53.928953,36.710560,0.026262,0.025836,0.024659,0.102049,0.110346,18,...,0.477790,8,1,147,34,1,0,0,1,34147
2931,9,4.0,45.495983,42.703410,0.021454,0.021753,0.005350,0.065958,0.082692,0,...,0.218671,3,2,147,34,1,0,0,1,34147
2932,10,3.0,17.765149,10.020055,0.077568,0.078281,0.019715,0.129249,0.100203,0,...,0.601054,1,0,147,34,1,0,0,1,34147
2933,11,5.0,6.148178,0.000000,0.033172,0.038167,0.031997,0.157557,0.156572,0,...,0.388025,0,0,147,34,1,0,0,1,34147

In [85]:
grouped = df3.groupby('panel_id')

In [7]:
df2=df_encoded

In [86]:
group_sizes = grouped.size()

In [87]:
max(group_sizes)

13

In [88]:
size={}
count=0
for i in group_sizes:
    if i not in size.keys():
        size[i]=1
    else:
        size[i]+=1
    count+=1

In [89]:
size

{13: 187, 12: 21, 6: 2, 9: 3, 8: 3, 10: 3, 11: 7, 7: 3}

In [90]:
count

229

In [79]:
panels=[group for group, df in grouped if len(df) > 5]

In [81]:
# panels

In [76]:
df3=df2

In [82]:
df3=df3[df3['panel_id'].isin(panels)]

In [83]:
df3

,time,MS_rating,Thumbstick_L,Thumbstick_R,Eye_Speed,Head_Speed,diff_Head_Eye_yaw,diff_Head_Eye_roll,diff_Head_Eye_pitch,Index_Trig_L,...,brightness_change,buttons,jumping,user_id,game_id,order,C,I,M,panel_id
0,0,1.0,0.000000,3.594337,0.090655,0.125845,0.023973,0.151847,0.103009,0,...,0.711018,0,0,5,1,2,0,0,1,1005
1,1,1.0,33.093972,62.157799,0.036334,0.036310,0.015407,0.139587,0.073105,8,...,0.802711,10,10,5,1,2,0,0,1,1005
2,2,1.0,46.027865,90.608110,0.042165,0.040388,0.021860,0.111357,0.075548,0,...,0.556988,6,6,5,1,2,0,0,1,1005
3,3,1.0,18.430878,5.229467,0.038978,0.037508,0.045567,0.123780,0.045428,23,...,0.597293,8,0,5,1,2,0,0,1,1005
4,4,1.0,26.719036,1.597837,0.117524,0.125837,0.038202,0.132651,0.063008,18,...,1.991390,0,0,5,1,2,0,0,1,1005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,2.0,103.000739,94.874378,0.021215,0.021257,0.008972,0.119471,0.088997,27,...,0.303524,5,0,147,34,1,0,0,1,34147
2930,8,5.0,53.928953,36.710560,0.026262,0.025836,0.024659,0.102049,0.110346,18,...,0.477790,8,1,147,34,1,0,0,1,34147
2931,9,4.0,45.495983,42.703410,0.021454,0.021753,0.005350,0.065958,0.082692,0,...,0.218671,3,2,147,34,1,0,0,1,34147
2932,10,3.0,17.765149,10.020055,0.077568,0.078281,0.019715,0.129249,0.100203,0,...,0.601054,1,0,147,34,1,0,0,1,34147
2933,11,5.0,6.148178,0.000000,0.033172,0.038167,0.031997,0.157557,0.156572,0,...,0.388025,0,0,147,34,1,0,0,1,34147

In [89]:
df3.to_csv("panel_data.csv",index=False)

In [91]:
df_encoded.to_csv("df_encoded.csv",index=False)

In [83]:
# df4= df3.drop('Unnamed: 0', axis=1)

KeyError: "['Unnamed: 0'] not found in axis"

In [28]:
df4

,time,MS_rating,Thumbstick_L,Thumbstick_Y,Eye_Speed,Head_Speed,diff_Head_Eye_yaw,diff_Head_Eye_roll,diff_Head_Eye_mean,Index_Trig_L,...,game_id,order,gender,Exp,hour,Right_handed,panel_id,C,I,M
0,0,1.0,0,3,0.090655,0.100112,0.006959,0.027844,-0.123867,0,...,1,2,1,1,11.0,1,1005,0,0,1
1,1,1.0,64,40,0.036334,0.026943,-0.002852,0.057525,-0.011762,8,...,1,2,1,1,11.0,1,1005,0,0,1
2,2,1.0,100,70,0.042165,0.027152,-0.000494,0.002223,-0.010256,0,...,1,2,1,1,11.0,1,1005,0,0,1
3,3,1.0,14,5,0.038978,0.024813,-0.014454,0.003437,0.041308,23,...,1,2,1,1,11.0,1,1005,0,0,1
4,4,1.0,22,5,0.117524,0.102146,0.004757,-0.092486,-0.028045,18,...,1,2,1,1,11.0,1,1005,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2871,8,2.0,88,12,0.025728,0.013219,-0.003462,-0.271966,-0.081005,0,...,34,1,1,0,18.0,1,34151,0,0,1
2872,9,2.0,39,28,0.028701,0.015984,-0.002912,-0.278688,-0.045081,0,...,34,1,1,0,18.0,1,34151,0,0,1
2873,10,2.0,120,38,0.020034,0.014363,-0.002458,-0.253725,-0.052810,0,...,34,1,1,0,18.0,1,34151,0,0,1
2874,11,3.0,50,16,0.052286,0.041861,-0.003896,-0.303288,-0.060112,0,...,34,1,1,0,18.0,1,34151,0,0,1
2875,12,2.0,60,9,0.018171,0.010422,-0.004395,-0.225103,-0.051528,0,...,34,1,1,0,18.0,1,34151,0,0,1

In [29]:
df4.to_csv('panel_data_4.csv', index=False)

In [7]:
df1=pd.read_csv("demo.csv")

In [7]:
with open('gamest.json', 'r') as file:
    # Load JSON data from the file
    gamest = json.load(file)

In [9]:
df1

,Unnamed: 0,Q1,Q2,Q3,Q6,timest,Unnamed: 6
0,2,18,Female,Once,NaN,1695708799000,NaN
1,3,18,Female,Once,NaN,1695708835000,19.0
2,4,27,Male,Few times a month,NaN,1695710945000,21.0
3,5,18,Male,Not at all,NaN,1695714654000,22.0
4,6,22,Female,Once,NaN,1695716894000,24.0
...,...,...,...,...,...,...,...
386,388,20,Female,Not at all,416.0,1701256296000,NaN
387,389,21,Male,Once,417.0,1701262202000,NaN
388,390,22,Female,Few times a year,418.0,1701263664000,NaN
389,391,22,Female,Few times a year,419.0,1701327700000,NaN
390,392,24,Male,Few times a year,420.0,1701442721000,NaN

In [9]:
def convert(epoch_milliseconds):
    epoch_seconds = epoch_milliseconds / 1000

# Create a datetime object from the Unix timestamp
    datetime_obj = datetime.datetime.fromtimestamp(epoch_seconds)

# Format the datetime object as a readable string
    formatted_date_time = datetime_obj.strftime('%Y-%m-%d %H:%M:%S')
    return formatted_date_time

# Print the readable date and time
# print("Readable Date and Time:", formatted_date_time)

In [12]:
times=df1['timest'].to_list()

In [10]:
import datetime
times2=[]
for i in times:
    times2.append(convert(i))

NameError: name 'times' is not defined

In [17]:
df1['tread']=times2

In [18]:
df1

,Unnamed: 0,Q1,Q2,Q3,Q6,timest,Unnamed: 6,tread
0,2,18,Female,Once,NaN,1695708799000,NaN,2023-09-26 14:13:19
1,3,18,Female,Once,NaN,1695708835000,19.0,2023-09-26 14:13:55
2,4,27,Male,Few times a month,NaN,1695710945000,21.0,2023-09-26 14:49:05
3,5,18,Male,Not at all,NaN,1695714654000,22.0,2023-09-26 15:50:54
4,6,22,Female,Once,NaN,1695716894000,24.0,2023-09-26 16:28:14
...,...,...,...,...,...,...,...,...
386,388,20,Female,Not at all,416.0,1701256296000,NaN,2023-11-29 19:11:36
387,389,21,Male,Once,417.0,1701262202000,NaN,2023-11-29 20:50:02
388,390,22,Female,Few times a year,418.0,1701263664000,NaN,2023-11-29 21:14:24
389,391,22,Female,Few times a year,419.0,1701327700000,NaN,2023-11-30 15:01:40
390,392,24,Male,Few times a year,420.0,1701442721000,NaN,2023-12-01 22:58:41

In [11]:
gamest2={}
for i in gamest.keys():
    gamest2[i]=convert(gamest[i]+18000000)

In [13]:
with open('gamest2.json', 'w') as file:
    json.dump(gamest2, file)

In [22]:
df1.to_csv("demo2.csv")

In [12]:
gamest2

{'7': '2023-09-25 19:01:46',
 '9': '2023-09-25 20:06:50',
 '6': '2023-09-25 18:06:12',
 '5': '2023-09-25 16:19:32',
 '8': '2023-09-25 19:06:23',
 '10': '2023-09-25 20:08:05',
 '145': '2023-10-06 21:16:35',
 '142': '2023-10-06 19:09:42',
 '141': '2023-10-06 19:05:21',
 '140': '2023-10-06 18:52:51',
 '135': '2023-10-06 14:04:28',
 '144': '2023-10-06 20:01:58',
 '143': '2023-10-06 20:01:40',
 '136': '2023-10-06 14:04:57',
 '137': '2023-10-06 14:59:10',
 '139': '2023-10-06 18:08:50',
 '138': '2023-10-06 15:03:26',
 '82': '2023-10-02 15:21:47',
 '79': '2023-09-30 21:33:00',
 '75': '2023-09-30 20:51:58',
 '77': '2023-09-30 21:24:14',
 '81': '2023-10-02 14:20:44',
 '74': '2023-09-30 19:28:38',
 '26': '2023-09-26 23:49:30',
 '27': '2023-09-27 14:12:54',
 '24': '2023-09-26 22:08:21',
 '22': '2023-09-26 21:17:32',
 '21': '2023-09-26 20:00:10',
 '30': '2023-09-27 15:06:46',
 '32': '2023-09-27 17:59:59',
 '37': '2023-09-27 23:08:34',
 '16': '2023-09-26 15:52:47',
 '18': '2023-09-26 18:29:30',
 '17': '2023-09-26 18:07:38',
 '15': '2023-09-26 15:18:20',
 '19': '2023-09-26 19:16:17',
 '12': '2023-09-25 22:12:41',
 '11': '2023-09-25 20:45:25',
 '134': '2023-10-06 14:08:21',
 '132': '2023-10-05 22:58:14',
 '133': '2023-10-05 22:58:31',
 '125': '2023-10-05 20:27:08',
 '130': '2023-10-05 21:53:31',
 '127': '2023-10-05 21:14:45',
 '126': '2023-10-05 21:05:29',
 '131': '2023-10-05 22:57:03',
 '129': '2023-10-05 21:54:28',
 '146': '2023-10-06 21:31:20',
 '148': '2023-10-06 22:17:08',
 '149': '2023-10-06 22:39:57',
 '155': '2023-10-07 14:56:12',
 '70': '2023-09-30 18:18:07',
 '66': '2023-09-30 15:16:36',
 '67': '2023-09-30 17:45:23',
 '71': '2023-09-30 18:23:00',
 '72': '2023-09-30 18:58:55',
 '61': '2023-09-29 22:22:45',
 '56': '2023-09-29 20:06:33',
 '58': '2023-09-29 20:08:10',
 '55': '2023-09-29 19:33:25',
 '60': '2023-09-29 21:11:08',
 '54': '2023-09-29 19:08:58',
 '63': '2023-09-29 22:33:44',
 '65': '2023-09-30 15:16:30',
 '68': '2023-09-30 17:44:22',
 '52': '2023-09-29 15:58:04',
 '44': '2023-09-28 16:01:57',
 '46': '2023-09-28 21:11:58',
 '51': '2023-09-29 15:58:48',
 '50': '2023-09-28 22:25:06',
 '48': '2023-09-28 21:36:30',
 '41': '2023-09-28 14:38:29',
 '35': '2023-09-27 21:07:59',
 '108': '2023-10-04 20:48:38',
 '109': '2023-10-04 22:18:34',
 '106': '2023-10-04 19:55:46',
 '114': '2023-10-04 23:02:47',
 '107': '2023-10-04 20:00:20',
 '111': '2023-10-04 22:23:08',
 '110': '2023-10-04 22:19:11',
 '104': '2023-10-04 19:04:54',
 '113': '2023-10-04 23:01:57',
 '105': '2023-10-04 18:58:16',
 '112': '2023-10-04 23:02:18',
 '115': '2023-10-05 14:19:16',
 '119': '2023-10-05 16:05:34',
 '124': '2023-10-05 19:06:35',
 '117': '2023-10-05 15:08:59',
 '123': '2023-10-05 19:08:18',
 '120': '2023-10-05 16:09:35',
 '122': '2023-10-05 19:05:40',
 '116': '2023-10-05 14:59:52',
 '118': '2023-10-05 15:36:53',
 '121': '2023-10-05 18:01:03',
 '85': '2023-10-02 19:09:44',
 '92': '2023-10-03 19:00:57',
 '89': '2023-10-03 17:57:13',
 '91': '2023-10-03 18:12:09',
 '84': '2023-10-02 19:01:40',
 '158': '2023-10-07 15:31:58',
 '160': '2023-10-07 16:50:22',
 '159': '2023-10-07 16:47:52',
 '165': '2023-10-07 19:04:15',
 '164': '2023-10-07 19:04:15',
 '163': '2023-10-07 19:04:15',
 '162': '2023-10-07 18:02:52',
 '157': '2023-10-07 15:23:30',
 '161': '2023-10-07 18:04:24',
 '156': '2023-10-07 15:12:02',
 '174': '2023-10-09 19:18:06',
 '173': '2023-10-09 18:03:19',
 '169': '2023-10-09 15:16:08',
 '166': '2023-10-07 20:09:34',
 '170': '2023-10-09 16:01:35',
 '167': '2023-10-07 20:11:25',
 '171': '2023-10-09 16:00:29',
 '168': '2023-10-09 14:28:34',
 '172': '2023-10-09 18:02:34',
 '101': '2023-10-03 23:00:30',
 '93': '2023-10-03 19:39:51',
 '97': '2023-10-03 21:07:02',
 '98': '2023-10-03 21:09:01',
 '95': '2023-10-03 20:02:19',
 '99': '2023-10-03 22:07:34',
 '150': '2023-10-06 23:10:37',
 '152': '2023-10-06 23:11:47',
 '153': '2023-10-07 01:02:22',
 '154': '2023-10-07 14:05:38',
 '151': '2023-10-06 23:08:34',
 '147': '2023-10-06 22:14:59'}

In [ ]:
df=pd.read_csv("data/panel_data")

In [72]:
df_encoded.to_csv("df_encoded.csv")

## Analysis 2

In [9]:
df=pd.read_csv("panel_data.csv")

In [91]:
df=df3

In [92]:
df['order']=df['order']-1

In [93]:
df

,time,MS_rating,Thumbstick_L,Thumbstick_R,Eye_Speed,Head_Speed,diff_Head_Eye_yaw,diff_Head_Eye_roll,diff_Head_Eye_pitch,Index_Trig_L,...,brightness_change,buttons,jumping,user_id,game_id,order,C,I,M,panel_id
0,0,1.0,0.000000,3.594337,0.090655,0.125845,0.023973,0.151847,0.103009,0,...,0.711018,0,0,5,1,1,0,0,1,1005
1,1,1.0,33.093972,62.157799,0.036334,0.036310,0.015407,0.139587,0.073105,8,...,0.802711,10,10,5,1,1,0,0,1,1005
2,2,1.0,46.027865,90.608110,0.042165,0.040388,0.021860,0.111357,0.075548,0,...,0.556988,6,6,5,1,1,0,0,1,1005
3,3,1.0,18.430878,5.229467,0.038978,0.037508,0.045567,0.123780,0.045428,23,...,0.597293,8,0,5,1,1,0,0,1,1005
4,4,1.0,26.719036,1.597837,0.117524,0.125837,0.038202,0.132651,0.063008,18,...,1.991390,0,0,5,1,1,0,0,1,1005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,2.0,103.000739,94.874378,0.021215,0.021257,0.008972,0.119471,0.088997,27,...,0.303524,5,0,147,34,0,0,0,1,34147
2930,8,5.0,53.928953,36.710560,0.026262,0.025836,0.024659,0.102049,0.110346,18,...,0.477790,8,1,147,34,0,0,0,1,34147
2931,9,4.0,45.495983,42.703410,0.021454,0.021753,0.005350,0.065958,0.082692,0,...,0.218671,3,2,147,34,0,0,0,1,34147
2932,10,3.0,17.765149,10.020055,0.077568,0.078281,0.019715,0.129249,0.100203,0,...,0.601054,1,0,147,34,0,0,0,1,34147
2933,11,5.0,6.148178,0.000000,0.033172,0.038167,0.031997,0.157557,0.156572,0,...,0.388025,0,0,147,34,0,0,0,1,34147

In [94]:
len(df['user_id'].unique())

128

In [95]:
len(df['game_id'].unique())

34

In [96]:
len(df['panel_id'].unique())

229

In [25]:
df.to_csv("panel_data_3.csv", index=False)

In [97]:
df

,time,MS_rating,Thumbstick_L,Thumbstick_R,Eye_Speed,Head_Speed,diff_Head_Eye_yaw,diff_Head_Eye_roll,diff_Head_Eye_pitch,Index_Trig_L,...,brightness_change,buttons,jumping,user_id,game_id,order,C,I,M,panel_id
0,0,1.0,0.000000,3.594337,0.090655,0.125845,0.023973,0.151847,0.103009,0,...,0.711018,0,0,5,1,1,0,0,1,1005
1,1,1.0,33.093972,62.157799,0.036334,0.036310,0.015407,0.139587,0.073105,8,...,0.802711,10,10,5,1,1,0,0,1,1005
2,2,1.0,46.027865,90.608110,0.042165,0.040388,0.021860,0.111357,0.075548,0,...,0.556988,6,6,5,1,1,0,0,1,1005
3,3,1.0,18.430878,5.229467,0.038978,0.037508,0.045567,0.123780,0.045428,23,...,0.597293,8,0,5,1,1,0,0,1,1005
4,4,1.0,26.719036,1.597837,0.117524,0.125837,0.038202,0.132651,0.063008,18,...,1.991390,0,0,5,1,1,0,0,1,1005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,2.0,103.000739,94.874378,0.021215,0.021257,0.008972,0.119471,0.088997,27,...,0.303524,5,0,147,34,0,0,0,1,34147
2930,8,5.0,53.928953,36.710560,0.026262,0.025836,0.024659,0.102049,0.110346,18,...,0.477790,8,1,147,34,0,0,0,1,34147
2931,9,4.0,45.495983,42.703410,0.021454,0.021753,0.005350,0.065958,0.082692,0,...,0.218671,3,2,147,34,0,0,0,1,34147
2932,10,3.0,17.765149,10.020055,0.077568,0.078281,0.019715,0.129249,0.100203,0,...,0.601054,1,0,147,34,0,0,0,1,34147
2933,11,5.0,6.148178,0.000000,0.033172,0.038167,0.031997,0.157557,0.156572,0,...,0.388025,0,0,147,34,0,0,0,1,34147

In [98]:
df['pre_MSR'] = df['MS_rating'].shift(1)

In [99]:
df

,time,MS_rating,Thumbstick_L,Thumbstick_R,Eye_Speed,Head_Speed,diff_Head_Eye_yaw,diff_Head_Eye_roll,diff_Head_Eye_pitch,Index_Trig_L,...,buttons,jumping,user_id,game_id,order,C,I,M,panel_id,pre_MSR
0,0,1.0,0.000000,3.594337,0.090655,0.125845,0.023973,0.151847,0.103009,0,...,0,0,5,1,1,0,0,1,1005,NaN
1,1,1.0,33.093972,62.157799,0.036334,0.036310,0.015407,0.139587,0.073105,8,...,10,10,5,1,1,0,0,1,1005,1.0
2,2,1.0,46.027865,90.608110,0.042165,0.040388,0.021860,0.111357,0.075548,0,...,6,6,5,1,1,0,0,1,1005,1.0
3,3,1.0,18.430878,5.229467,0.038978,0.037508,0.045567,0.123780,0.045428,23,...,8,0,5,1,1,0,0,1,1005,1.0
4,4,1.0,26.719036,1.597837,0.117524,0.125837,0.038202,0.132651,0.063008,18,...,0,0,5,1,1,0,0,1,1005,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,2.0,103.000739,94.874378,0.021215,0.021257,0.008972,0.119471,0.088997,27,...,5,0,147,34,0,0,0,1,34147,3.0
2930,8,5.0,53.928953,36.710560,0.026262,0.025836,0.024659,0.102049,0.110346,18,...,8,1,147,34,0,0,0,1,34147,2.0
2931,9,4.0,45.495983,42.703410,0.021454,0.021753,0.005350,0.065958,0.082692,0,...,3,2,147,34,0,0,0,1,34147,5.0
2932,10,3.0,17.765149,10.020055,0.077568,0.078281,0.019715,0.129249,0.100203,0,...,1,0,147,34,0,0,0,1,34147,4.0
2933,11,5.0,6.148178,0.000000,0.033172,0.038167,0.031997,0.157557,0.156572,0,...,0,0,147,34,0,0,0,1,34147,3.0

In [100]:
df = df[df['time'] != 0]

In [101]:
df

,time,MS_rating,Thumbstick_L,Thumbstick_R,Eye_Speed,Head_Speed,diff_Head_Eye_yaw,diff_Head_Eye_roll,diff_Head_Eye_pitch,Index_Trig_L,...,buttons,jumping,user_id,game_id,order,C,I,M,panel_id,pre_MSR
1,1,1.0,33.093972,62.157799,0.036334,0.036310,0.015407,0.139587,0.073105,8,...,10,10,5,1,1,0,0,1,1005,1.0
2,2,1.0,46.027865,90.608110,0.042165,0.040388,0.021860,0.111357,0.075548,0,...,6,6,5,1,1,0,0,1,1005,1.0
3,3,1.0,18.430878,5.229467,0.038978,0.037508,0.045567,0.123780,0.045428,23,...,8,0,5,1,1,0,0,1,1005,1.0
4,4,1.0,26.719036,1.597837,0.117524,0.125837,0.038202,0.132651,0.063008,18,...,0,0,5,1,1,0,0,1,1005,1.0
5,5,1.0,47.349634,26.812417,0.063776,0.062262,0.028084,0.146265,0.054504,80,...,10,10,5,1,1,0,0,1,1005,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,2.0,103.000739,94.874378,0.021215,0.021257,0.008972,0.119471,0.088997,27,...,5,0,147,34,0,0,0,1,34147,3.0
2930,8,5.0,53.928953,36.710560,0.026262,0.025836,0.024659,0.102049,0.110346,18,...,8,1,147,34,0,0,0,1,34147,2.0
2931,9,4.0,45.495983,42.703410,0.021454,0.021753,0.005350,0.065958,0.082692,0,...,3,2,147,34,0,0,0,1,34147,5.0
2932,10,3.0,17.765149,10.020055,0.077568,0.078281,0.019715,0.129249,0.100203,0,...,1,0,147,34,0,0,0,1,34147,4.0
2933,11,5.0,6.148178,0.000000,0.033172,0.038167,0.031997,0.157557,0.156572,0,...,0,0,147,34,0,0,0,1,34147,3.0

In [5]:
df_encoded=pd.read_csv("df_encoded.csv")

In [6]:
df_encoded

,time,MS_rating,Thumbstick_L,Thumbstick_R,Eye_Speed,Head_Speed,diff_Head_Eye_yaw,diff_Head_Eye_roll,diff_Head_Eye_mean,Index_Trig_L,...,brightness_change,buttons,jumping,user_id,game_id,order,C,I,M,panel_id
0,0,1.0,0.000000,3.594337,0.090655,0.125845,0.006959,0.025243,-0.020902,0,...,0.711018,0,0,5,1,2,0,0,1,1005
1,1,1.0,33.093972,62.157799,0.036334,0.036310,-0.002852,0.103825,-0.029015,8,...,0.802711,10,10,5,1,2,0,0,1,1005
2,2,1.0,46.027865,90.608110,0.042165,0.040388,-0.000494,0.059899,-0.003239,0,...,0.556988,6,6,5,1,2,0,0,1,1005
3,3,1.0,18.430878,5.229467,0.038978,0.037508,-0.014454,-0.054388,0.026130,23,...,0.597293,8,0,5,1,2,0,0,1,1005
4,4,1.0,26.719036,1.597837,0.117524,0.125837,0.004757,0.040297,-0.022944,18,...,1.991390,0,0,5,1,2,0,0,1,1005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,2.0,103.000739,94.874378,0.021215,0.021257,-0.002803,-0.117032,-0.042114,27,...,0.303524,5,0,147,34,1,0,0,1,34147
2930,8,5.0,53.928953,36.710560,0.026262,0.025836,0.002527,-0.082279,-0.038337,18,...,0.477790,8,1,147,34,1,0,0,1,34147
2931,9,4.0,45.495983,42.703410,0.021454,0.021753,-0.002140,-0.061502,-0.076433,0,...,0.218671,3,2,147,34,1,0,0,1,34147
2932,10,3.0,17.765149,10.020055,0.077568,0.078281,-0.001054,-0.110166,-0.059406,0,...,0.601054,1,0,147,34,1,0,0,1,34147
2933,11,5.0,6.148178,0.000000,0.033172,0.038167,-0.022093,-0.073912,-0.107088,0,...,0.388025,0,0,147,34,1,0,0,1,34147

In [23]:
df1=pd.read_csv("/data/VR_NET/folders/Barnyard/165_1_Barnyard/data_file.csv")

In [21]:
ls /data/VR_NET/folders/Barnyard/165_1_Barnyard/

data_file.csv  video/

In [24]:
df1[df1['MS_rating']>0]

,frame,timestamp,head_dir,head_pos,head_vel,head_angvel,left_eye_dir,left_eye_pos,left_eye_vel,left_eye_angvel,...,video,MS_rating,left_controller_dir,left_controller_pos,left_controller_vel,left_controller_angvel,right_controller_dir,right_controller_pos,right_controller_vel,right_controller_angvel
728,7280,1696658789063,"(0.06214965134859085, 0.23935258388519287, -0....","(0.06169329583644867, 0.016743868589401245, 0....","(-0.015999477356672287, -0.0019650310277938843...","(-0.01286863349378109, 0.2563773989677429, -0....","(0.06214965134859085, 0.23935258388519287, -0....","(0.09164998680353165, 0.016545535996556282, 0....","(-0.015999477356672287, -0.0019650310277938843...","(-0.01286863349378109, 0.2563773989677429, -0....",...,video/7280,1.0,"(0.1088920459151268, 0.059496477246284485, 0.0...","(-0.008650440722703934, -0.3317798376083374, -...","(-0.01308341696858406, 0.019472815096378326, 0...","(0.13562162220478058, 0.016822632402181625, -0...","(0.08669247478246689, -0.04497194290161133, -0...","(0.2079591155052185, -0.340203195810318, -0.14...","(-0.048845842480659485, -0.022712720558047295,...","(-0.18651798367500305, 0.1704285889863968, -0...."
1266,12660,1696658866979,"(-0.03377611190080643, 0.09346786141395569, -0...","(0.10028326511383057, -0.009699353016912937, 0...","(-0.015136027708649635, 0.0019417712464928627,...","(-0.001529342494904995, 0.06673464924097061, 0...","(-0.03377611190080643, 0.09346786141395569, -0...","(0.1335504949092865, -0.01005117129534483, 0.1...","(-0.015136027708649635, 0.0019417712464928627,...","(-0.001529342494904995, 0.06673464924097061, 0...",...,video/12660,2.0,"(0.17970915138721466, 0.04645940661430359, -0....","(0.04540615901350975, -0.26719552278518677, -0...","(-0.03665924072265625, 0.012306387536227703, 0...","(0.09992466866970062, -0.056529827415943146, 0...","(0.19596590101718903, -0.05957069993019104, -0...","(0.240321084856987, -0.2865934371948242, -0.11...","(-0.009811989031732082, -0.006652435287833214,...","(-0.03423142060637474, 0.010838677175343037, 0..."
1716,17160,1696658932940,"(-0.019773097708821297, 0.12685154378414154, -...","(0.09936599433422089, -0.0054129427298903465, ...","(-0.0016521639190614223, 0.0001806205400498584...","(-0.003547011176124215, -0.0070000020787119865...","(-0.019773097708821297, 0.12685154378414154, -...","(0.13213346898555756, -0.005945069249719381, 0...","(-0.0016521639190614223, 0.0001806205400498584...","(-0.003547011176124215, -0.0070000020787119865...",...,video/17160,2.0,"(0.20878157019615173, 0.14816854894161224, -0....","(0.0053819408640265465, -0.24995671212673187, ...","(0.009209061041474342, 0.010769636370241642, -...","(-0.0005790963768959045, 0.27698174118995667, ...","(0.23822413384914398, -0.014821529388427734, -...","(0.21331888437271118, -0.245631143450737, -0.1...","(0.0008570090285502374, -8.282491035060957e-05...","(0.004895161371678114, -0.0028482135385274887,..."
2006,20060,1696658977947,"(0.05410807952284813, 0.043894603848457336, -0...","(0.10783036798238754, 0.00563309621065855, 0.1...","(0.022426696494221687, 0.011541690677404404, -...","(0.12282611429691315, -0.34432050585746765, -0...","(0.05410807952284813, 0.043894603848457336, -0...","(0.14145557582378387, 0.003155732061713934, 0....","(0.022426696494221687, 0.011541690677404404, -...","(0.12282611429691315, -0.34432050585746765, -0...",...,video/20060,1.0,"(0.11612845212221146, 0.0625184178352356, 0.05...","(0.04124148190021515, -0.29229918122291565, -0...","(0.06542889028787613, -0.0023671973031014204, ...","(-0.042244553565979004, -0.17641082406044006, ...","(0.21456125378608704, -0.006988883018493652, -...","(0.20364674925804138, -0.2693418264389038, -0....","(0.06497135758399963, 0.005047541111707687, 0....","(0.009687758982181549, -0.20455950498580933, 0..."
2358,23580,1696659030996,"(0.04965290054678917, 0.16500002145767212, -0....","(0.15837478637695312, -0.006716028321534395, 0...","(-0.001989003736525774, 0.0006068121874704957,...","(-0.006561290472745895, -0.03655782341957092, ...","(0.04965290054678917, 0.16500002145767212, -0....","(0.19027987122535706, -0.008852286264300346, 0...","(-0.001989003736525774, 0.0006068121874704957,...","(-0.006561290472745895, -0.03655782341957092, ...",...,video/23580,2.0,"(0.1844465583562851, 0.02051904797554016, 0.13...","(0.09839869290590286, -0.2791914641857147, 0.0...","(0.01974118873476982, 0.014752138406038284, 0....","(0.1735880821943283, -0.17387554049491882, -0....","(0.23419144749641418, -0.004484653472900391, -...","(0.2623218595981598, -0.2689078450202942, -0.0...","(-0.0044237542897462845, 0.006478970404714346,...","(0.011842108331620693, 0.004316157661378384, 0..."
2798,27980,1696659099021,"(-0.006386667024344206, -0.09891802072525024, ...","(0.2512456774711609, -0.02425834909081459, 0.1...","(0.016410723328590393, 0.0002526278840377927, ...","(-0.009979557245969772, -0.07493951916694641, ...","(-0.006386667024344206, -0.09891802072525024, ...","(0.2843945026397705, -0.026003098115324974, 0....","(0.016410723328590393, 0.0002526278840377927, ...","(-0.009979557245969772, -0.07493951916694641, ...",...,video/27980,4.0,"(-0.013335982337594032, 0.13170693814754486, 0...","(0.1545894593000412, -0.39136579632759094, -0....","(0.11694464087486267, -0.03703790158033371, -0...","(-0.1494160294532776, -0.23731756210327148, -0...","(-0.017858006060123444, -0.22511926293373108, ...","(0.40901505947113037, -0.3378044366836548, -0....","(-0.09581058472394943, -0.000693341251462698, ...","(-0.01300022378563881, 0.4452250599861145, -0...."
3313,33130,1696659175984,"(0.012282636016607285, -0.041127413511276245, ...","(0.3436615765094757, -0.0008486880687996745, 0...","(-0.011532029137015343, 0.001270804088562727, ...","(-0.024888884276151657, 0.022992797195911407, ...","(0.012282636016607285, -0.041127413511276245, ...","(0.3773495554924011, 0.0010722661390900612, 0....","(-0.011532029137015343, 0.001270804088562727, ...","(-0.024888884276151657, 0.022992797195911407, ...",...,video/33130,3.0,"(0.039304256439208984, -0.014048129320144653, ...","(0.30887535214424133, -0.3543405830860138, -0....","(-0.030026694759726524, -0.005222992971539497,...","(-0.11443211138248444, 0.028828643262386322, 0...","(0.01412247121334076, -0.15988773107528687, 0....","(0.5014895796775818, -0.37731364369392395, -0....","(-0.007177155464887619, 0.529812216758728, -0....","(0.9499025940895081, 0.17626161873340607, 0.18..."
3621,36210,1696659224078,"(-0.0369119718670845, -0.10841162502765656, 0....","(0.3461146950721741, -0.012996632605791092, 0....","(0.0023015933111310005, 0.004495561122894287, ...","(0.02921832911670208, -0.040092382580041885, -...","(-0.036911968141794205, -0.10841161012649536, ...","(0.3788772523403168, -0.008253296837210655, 0....","(0.0023015933111310005, 0.004495561122894287, ...","(0.02921832911670208, -0.040092382580041885, -...",...,video/36210,4.0,"(0.01569896563887596, -0.08400142192840576, 0....","(0.34983518719673157, -0.3602777421474457, -0....","(-0.001739956671372056, 0.013230793178081512, ...","(0.026524923741817474, 0.023798326030373573, 0...","(0.04595033824443817, -0.12917128205299377, -0...","(0.5322222113609314, -0.35771530866622925, -0....","(-0.031178701668977737, 0.02690228261053562, -...","(0.09747994691133499, 0.09336945414543152, -0...."
3954,39540,1696659277000,"(0.058342646807432175, 0.05729256570339203, -0...","(0.3690466582775116, 0.003300765063613653, 0.0...","(0.002165374578908086, -0.0036000367254018784,...","(-0.017337795346975327, 0.06419713795185089, 0...","(0.058342646807432175, 0.05729256570339203, -0...","(0.40232476592063904, -0.001371988095343113, 0...","(0.002165374578908086, -0.0036000367254018784,...","(-0.017337795346975327, 0.06419713795185089, 0...",...,video/39540,4.0,"(-0.03226952999830246, -0.007390528917312622, ...","(0.3002112805843353, -0.38264375925064087, -0....","(-0.0007098616333678365, 0.016098657622933388,...","(0.2520701587200165, 0.16712555289268494, -0.3...","(0.014942999929189682, 0.020217865705490112, -...","(0.4948594272136688, -0.3908778429031372, -0.1...","(0.005350156221538782, 0.0075075021013617516, ...","(0.024828992784023285, 0.007689557503908873, -..."
4160,41600,1696659312998,"(0.0681716650724411, -0.024563074111938477, -0...","(0.38396185636520386, 0.0033397332299500704, 0...","(-0.008676769211888313, 0.0007826964720152318,...","(0.0011880616657435894, 0.02346133626997471, 0...","(0.0681716650724411, -0.024563074111938477, -0...","(0.41711223125457764, -0.003447767812758684, 0...","(-0.008676769211888313, 0.0007826964720152318,...","(0.0011880616657435894, 0.02346133626997471, 0...",...,video/41600,3.0,"(-0.06758619844913483, 0.021256566047668457, -...","(0.29854288697242737, -0.3796829581260681, -0....","(-0.0013262731954455376, -0.002442218828946352...","(-0.01414805743843317, 0.007768825627863407, 0...","(0.039247918874025345, -0.01652812957763672, -...","(0.5041995048522949, -0.3830094635486603, -0.1...","(-0.014395171776413918, 0.005694163031876087, ...","(0.01999504864215851, 0.048450831323862076, 0...."
4356,43560,1696659344989,"(0.18619820475578308, -0.2710147202014923, 0.0...","(0.41061466932296753, 0.02691955491900444, 0.0...","(0.04916306585073471, -0.001621447503566742, 0...","(0.28674042224884033, 0.04620799049735069, -0....","(0.18619820475578308, -0.2710147202014923, 0.0...","(0.4394978880882263, 0.023855986073613167, 0.0...","(0.04916306585073471, -0.001621447503566742, 0...","(0.28674042224884033, 0.04620799049735069, -0....",...,video/43560,3.0,"(-0.09729108214378357, -0.055881887674331665, ...","(0.34736743569374084, -0.39940115809440613, -0...","(0.01142457127571106, -0.031031284481287003, -...","(-0.10153216123580933, -0.06476807594299316, -...","(0.043917614966630936, -0.11750075221061707, -...","(0.5586093068122864, -0.38574302196502686, -0....","(0.01991732232272625, -0.025473881512880325, 0...","(-0.081476129591465, -0.09976653009653091, -0...."
4672,46720,1696659395954,"(0.05435105413198471, -0.4967188537120819, -0....","(0.4462788701057434, -0.0035142176784574986, 0...","(0.01916731335222721, -0.00118260458111763, 0....","(-0.0487268827855587, 0.011596288532018661, -0...","(0.05435105413198471, -0.4967188537120819, -0....","(0.46334874629974365, -0.007371506653726101, 0...","(0.01916731335222721, -0.00118260458111763, 0....","(-0.0487268827855587, 0.011596288532018661, -0...",...,video/46720,4.0,"(-0.03283121809363365, -0.20268931984901428, -...","(0.4495914578437805, -0.33992496132850647, -0....","(-0.0036691478453576565, -0.03207606077194214,...","(-0.3588232398033142, 0.0688195750117302, -0.0...","(0.06195826828479767, -0.22425416111946106, -0...","(0.5821781754493713, -0.3543263077735901, -0.0...","(-0.0005157414125278592, -0.000384195504011586...","(0.014035165309906006, 0.021726612001657486, 0..."
5047,50470,1696659456962,"(-0.2856915295124054, -0.14082999527454376, -0...","(0.3804246783256531, -0.07969414442777634, 0.0...","(0.008344761095941067, 0.00725913280621171, -0...","(0.0494382306933403, 0.03206717595458031, 0.02...","(-0.285691499710083, -0.14082998037338257, -0....","(0.41291213035583496, -0.07828893512487411, 0....","(0.008344761095941067, 0.00725913280621171, -0...","(0.0494382306933403, 0.03206717595458031, 0.02...",...,video/50470,4.0,"(-0.053366195410490036, -0.06373921036720276, ...","(0.36866968870162964, -0.3783000409603119, -0....","(-0.04497953876852989, -0.008253038860857487, ...","(-0.11343254894018173, 0.11283418536186218, 0....","(0.012096058577299118, -0.17339438199996948, -...","(0.554138720035553, -0.3634531497955322, -0.09...","(-0.0055366032756865025, -0.026357179507613182...","(-0.07821796834468842, 0.04054011404514313, 0...."
5447,54470,1696659516051,"(0.0019952822476625443, -0.24057435989379883, ...","(0.44171613454818726, -0.00832066684961319, 0....","(0.025038404390215874, 0.009898095391690731, -...","(0.051565513014793396, -0.31281551718711853, -...","(0.0019952822476625443, -0.24057435989379883, ...","(0.47139137983322144, -0.012453367002308369, 0...","(0.025038404390215874, 0.009898095391690731, -...","(0.051565513014793396, -0.31281551718711853, -...",...,video/54470,3.0,"(-0.17742924392223358, -0.13650944828987122, 0...","(0.4198334217071533, -0.39602917432785034, -0....","(0.16708128154277802, 0.04964037984609604, 0.0...","(0.34096425771713257, -0.5082770586013794, -0....","(-0.032879702746868134, -0.23010167479515076, ...","(0.6411632299423218, -0.3800683617591858, -0.0...","(0.15777507424354553, 0.031919002532958984, 0....","(0.08810406178236008, -0.55228191614151, 0.047..."

In [102]:
df

,time,MS_rating,Thumbstick_L,Thumbstick_R,Eye_Speed,Head_Speed,diff_Head_Eye_yaw,diff_Head_Eye_roll,diff_Head_Eye_pitch,Index_Trig_L,...,buttons,jumping,user_id,game_id,order,C,I,M,panel_id,pre_MSR
1,1,1.0,33.093972,62.157799,0.036334,0.036310,0.015407,0.139587,0.073105,8,...,10,10,5,1,1,0,0,1,1005,1.0
2,2,1.0,46.027865,90.608110,0.042165,0.040388,0.021860,0.111357,0.075548,0,...,6,6,5,1,1,0,0,1,1005,1.0
3,3,1.0,18.430878,5.229467,0.038978,0.037508,0.045567,0.123780,0.045428,23,...,8,0,5,1,1,0,0,1,1005,1.0
4,4,1.0,26.719036,1.597837,0.117524,0.125837,0.038202,0.132651,0.063008,18,...,0,0,5,1,1,0,0,1,1005,1.0
5,5,1.0,47.349634,26.812417,0.063776,0.062262,0.028084,0.146265,0.054504,80,...,10,10,5,1,1,0,0,1,1005,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,2.0,103.000739,94.874378,0.021215,0.021257,0.008972,0.119471,0.088997,27,...,5,0,147,34,0,0,0,1,34147,3.0
2930,8,5.0,53.928953,36.710560,0.026262,0.025836,0.024659,0.102049,0.110346,18,...,8,1,147,34,0,0,0,1,34147,2.0
2931,9,4.0,45.495983,42.703410,0.021454,0.021753,0.005350,0.065958,0.082692,0,...,3,2,147,34,0,0,0,1,34147,5.0
2932,10,3.0,17.765149,10.020055,0.077568,0.078281,0.019715,0.129249,0.100203,0,...,1,0,147,34,0,0,0,1,34147,4.0
2933,11,5.0,6.148178,0.000000,0.033172,0.038167,0.031997,0.157557,0.156572,0,...,0,0,147,34,0,0,0,1,34147,3.0

In [104]:
df.to_csv("panel_data_1.csv", index=False)

## demo

In [5]:
df=pd.read_csv("/home/dinithi/MSRatingSummary1.csv")

In [6]:
df

,Session,MS_rating,mean_MSR
0,181_1_Barbie,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.000000
1,184_1_Barbie,"[2.0, 1.0, 2.0, 2.0, 1.0, 3.0, 3.0, 3.0, 3.0, ...",2.384615
2,178_1_Barbie,"[1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.384615
3,183_1_Barbie,"[1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 1.0, ...",1.230769
4,187_1_Barbie,"[1.0, 1.0, 2.0, 3.0, 2.0, 3.0, 1.0, 1.0, 1.0, ...",1.769231
...,...,...,...
788,294_1_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.000000
789,289_2_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.000000
790,298_1_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 2.0, 3.0, 3.0, 3.0, 4.0, 4.0, ...",3.000000
791,292_1_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, ...",1.461538
792,297_1_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 2.0, 2.0, ...",1.692308

In [7]:
df1=df

In [8]:
df1

,Session,MS_rating,mean_MSR
0,181_1_Barbie,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.000000
1,184_1_Barbie,"[2.0, 1.0, 2.0, 2.0, 1.0, 3.0, 3.0, 3.0, 3.0, ...",2.384615
2,178_1_Barbie,"[1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.384615
3,183_1_Barbie,"[1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 1.0, ...",1.230769
4,187_1_Barbie,"[1.0, 1.0, 2.0, 3.0, 2.0, 3.0, 1.0, 1.0, 1.0, ...",1.769231
...,...,...,...
788,294_1_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.000000
789,289_2_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.000000
790,298_1_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 2.0, 3.0, 3.0, 3.0, 4.0, 4.0, ...",3.000000
791,292_1_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, ...",1.461538
792,297_1_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 2.0, 2.0, ...",1.692308

In [18]:
def parse_string(s):
    parts = s.split('_')
    participant_id = parts[0]
    order = parts[1]
    game_name = '_'.join(parts[2:])  # Join back any remaining parts which might contain underscores
    return participant_id, order, game_name

def find_first_five(ratings):
    observed=0
    try:
        index = ratings.index(5)
        observed=1
        return index , observed
    except ValueError:
        return 12 , observed

In [12]:
session=df1['Session'].to_list()

In [15]:
msr=df1['MS_rating'].to_list()
msr1 = [ast.literal_eval(sl) for sl in msr]

In [19]:
game_name=[]
user_id=[]
order=[]
timetodrop=[]
dropped=[]

for i in session:
    game_name.append(parse_string(i)[2])
    user_id.append(parse_string(i)[0])
    order.append(parse_string(i)[1])
    
for i in msr1:
    timetodrop.append(find_first_five(i)[0])
    dropped.append(find_first_five(i)[1])

In [20]:
df1['game_name']=game_name
df1['user_id']=user_id
df1['order']= order
df1['timetodrop']=timetodrop
df1['dropped']=dropped

In [21]:
df1

,Session,MS_rating,mean_MSR,game_name,user_id,order,timetodrop,dropped
0,181_1_Barbie,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.000000,Barbie,181,1,12,0
1,184_1_Barbie,"[2.0, 1.0, 2.0, 2.0, 1.0, 3.0, 3.0, 3.0, 3.0, ...",2.384615,Barbie,184,1,12,0
2,178_1_Barbie,"[1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.384615,Barbie,178,1,12,0
3,183_1_Barbie,"[1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 1.0, ...",1.230769,Barbie,183,1,12,0
4,187_1_Barbie,"[1.0, 1.0, 2.0, 3.0, 2.0, 3.0, 1.0, 1.0, 1.0, ...",1.769231,Barbie,187,1,12,0
...,...,...,...,...,...,...,...,...
788,294_1_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.000000,Man_of_Moon_Mountain,294,1,12,0
789,289_2_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.000000,Man_of_Moon_Mountain,289,2,12,0
790,298_1_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 2.0, 3.0, 3.0, 3.0, 4.0, 4.0, ...",3.000000,Man_of_Moon_Mountain,298,1,12,1
791,292_1_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, ...",1.461538,Man_of_Moon_Mountain,292,1,12,0
792,297_1_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 2.0, 2.0, ...",1.692308,Man_of_Moon_Mountain,297,1,12,0

In [22]:
sum(df['dropped'])

94

In [31]:
demo=pd.read_csv("/home/dinithi/Demographic_Horizon_Study.csv")

In [32]:
demo

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,ExternalReference,LocationLatitude,LocationLongitude,DistributionChannel,UserLanguage,Q1,Q2,Q3,Q4,Q6
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,External Data Reference,Location Latitude,Location Longitude,Distribution Channel,User Language,What is your age?,Gender,Have you ever used a VR application?,Are you familiar with VR interfaces?,Participant ID
1,"{""ImportId"":""startDate"",""timeZone"":""Pacific/Au...","{""ImportId"":""endDate"",""timeZone"":""Pacific/Auck...","{""ImportId"":""status""}","{""ImportId"":""ipAddress""}","{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}","{""ImportId"":""recordedDate"",""timeZone"":""Pacific...","{""ImportId"":""_recordId""}","{""ImportId"":""recipientLastName""}",...,"{""ImportId"":""externalDataReference""}","{""ImportId"":""locationLatitude""}","{""ImportId"":""locationLongitude""}","{""ImportId"":""distributionChannel""}","{""ImportId"":""userLanguage""}","{""ImportId"":""QID123619341_TEXT""}","{""ImportId"":""QID123619342""}","{""ImportId"":""QID123619343""}","{""ImportId"":""QID123619344""}","{""ImportId"":""QID6_TEXT""}"
2,2023-09-26 14:13:19,2023-09-26 14:13:43,IP Address,137.132.212.136,100,24,True,2023-09-26 14:13:44,R_3D1rJvTPSLf3DC0,NaN,...,NaN,1.2929,103.8547,anonymous,EN,18,Female,Once,Novice,NaN
3,2023-09-26 14:13:55,2023-09-26 14:14:09,Spam,137.132.212.136,100,14,True,2023-09-26 14:14:10,R_570TXWaAISvyTTP,NaN,...,NaN,1.2929,103.8547,anonymous,EN,18,Female,Once,Novice,NaN
4,2023-09-26 14:49:05,2023-09-26 15:50:17,IP Address,104.28.119.110,100,3672,True,2023-09-26 15:50:18,R_12A4SbKtSB5PZ9i,NaN,...,NaN,1.2929,103.8547,anonymous,EN,27,Male,Few times a month,-,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388,2023-11-29 19:11:36,2023-11-29 19:47:59,IP Address,137.132.218.137,100,2183,True,2023-11-29 19:48:00,R_24vcoK2kJm98jsl,NaN,...,NaN,1.2868,103.8503,anonymous,EN,20,Female,Not at all,-,416
389,2023-11-29 20:50:02,2023-11-29 21:14:11,IP Address,122.11.212.212,100,1448,True,2023-11-29 21:14:12,R_305M9GBxOQZGCzh,NaN,...,NaN,1.3248,103.8566,anonymous,EN,21,Male,Once,-,417
390,2023-11-29 21:14:24,2023-11-29 22:06:49,IP Address,122.11.212.212,100,3145,True,2023-11-29 22:06:50,R_YXi6hBRWbwBOTcZ,NaN,...,NaN,1.3248,103.8566,anonymous,EN,22,Female,Few times a year,-,418
391,2023-11-30 15:01:40,2023-11-30 15:02:35,IP Address,137.132.217.135,100,54,True,2023-11-30 15:02:35,R_1ghk495g048cJPX,NaN,...,NaN,1.2868,103.8503,anonymous,EN,22,Female,Few times a year,Neutral,419
392,2023-12-01 22:58:41,2023-12-01 23:01:19,IP Address,122.11.214.2,100,157,True,2023-12-01 23:01:20,R_2E9VbtIFjHLzwRc,NaN,...,NaN,1.3596,103.8637,anonymous,EN,24,Male,Few times a year,-,420

In [33]:
demodf=demo[['StartDate', 'EndDate', 'Q1', 'Q2', 'Q3', 'Q6']]
demodf=demodf[2:]
# merged_df = pd.merge(panel, demo1, on='user_id', how='left')

In [36]:
demodf=demodf[['Q1','Q2','Q3','Q6']]

In [37]:
demodf

     Q1      Q2                 Q3   Q6
2    18  Female               Once  NaN
3    18  Female               Once  NaN
4    27    Male  Few times a month  NaN
5    18    Male         Not at all  NaN
6    22  Female               Once  NaN
..   ..     ...                ...  ...
388  20  Female         Not at all  416
389  21    Male               Once  417
390  22  Female   Few times a year  418
391  22  Female   Few times a year  419
392  24    Male   Few times a year  420

[391 rows x 4 columns]

In [ ]:
# merged_df = pd.merge(df1, demodf, on='user_id', how='left')

In [38]:
demodf = demodf.rename(columns={
    'Q1': 'age',
    'Q2': 'gender',
    'Q3': 'pre_exp',
    'Q6': 'user_id',
})

In [39]:
merged_df = pd.merge(df1, demodf, on='user_id', how='left')

In [40]:
merged_df

,Session,MS_rating,mean_MSR,game_name,user_id,order,timetodrop,dropped,age,gender,pre_exp
0,181_1_Barbie,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.000000,Barbie,181,1,12,0,NaN,NaN,NaN
1,184_1_Barbie,"[2.0, 1.0, 2.0, 2.0, 1.0, 3.0, 3.0, 3.0, 3.0, ...",2.384615,Barbie,184,1,12,0,NaN,NaN,NaN
2,178_1_Barbie,"[1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.384615,Barbie,178,1,12,0,NaN,NaN,NaN
3,183_1_Barbie,"[1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 1.0, ...",1.230769,Barbie,183,1,12,0,NaN,NaN,NaN
4,187_1_Barbie,"[1.0, 1.0, 2.0, 3.0, 2.0, 3.0, 1.0, 1.0, 1.0, ...",1.769231,Barbie,187,1,12,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
799,294_1_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.000000,Man_of_Moon_Mountain,294,1,12,0,37,Male,Once
800,289_2_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.000000,Man_of_Moon_Mountain,289,2,12,0,NaN,NaN,NaN
801,298_1_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 2.0, 3.0, 3.0, 3.0, 4.0, 4.0, ...",3.000000,Man_of_Moon_Mountain,298,1,12,1,24,Male,Few times a year
802,292_1_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, ...",1.461538,Man_of_Moon_Mountain,292,1,12,0,24,Female,Once
803,297_1_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 2.0, 2.0, ...",1.692308,Man_of_Moon_Mountain,297,1,12,0,26,Female,Few times a week

In [ ]:
drop

In [41]:
merged_df = merged_df.dropna()

In [45]:
merged_df1=merged_df[['game_name', 'user_id', 'order',
       'timetodrop', 'dropped', 'age', 'gender', 'pre_exp']]

In [43]:
merged_df.columns

Index(['Session', 'MS_rating', 'mean_MSR', 'game_name', 'user_id', 'order',
       'timetodrop', 'dropped', 'age', 'gender', 'pre_exp'],
      dtype='object')

In [46]:
merged_df1

,game_name,user_id,order,timetodrop,dropped,age,gender,pre_exp
11,Escape_Puzzle_Mansion,311,1,12,0,22,Male,Not at all
12,Escape_Puzzle_Mansion,309,1,10,1,21,Female,Not at all
13,Escape_Puzzle_Mansion,317,1,10,1,21,Male,Once
15,Escape_Puzzle_Mansion,315,1,12,0,35,Male,Once
16,Escape_Puzzle_Mansion,316,1,12,0,21,Female,Once
...,...,...,...,...,...,...,...,...
798,Man_of_Moon_Mountain,294,1,12,0,24,Male,Not at all
799,Man_of_Moon_Mountain,294,1,12,0,37,Male,Once
801,Man_of_Moon_Mountain,298,1,12,1,24,Male,Few times a year
802,Man_of_Moon_Mountain,292,1,12,0,24,Female,Once
803,Man_of_Moon_Mountain,297,1,12,0,26,Female,Few times a week

In [47]:
sum(merged_df1['dropped'])

51

In [48]:
game_abbs={'Earth_Gym': 1,
 'Wild_Quest': 2,
 'Roommate': 3,
 'Waffle_Restaurant': 4,
 'Superhero_Arena': 5,
 'Army_Men': 6,
 'Bobber_Bay_Fishing': 7,
 'Citadel': 8,
 'Mars_Miners': 9,
 'American_Idol': 10,
 'Kawaii_Daycare': 11,
 'Giant_Paddle_Golf': 12,
 'City_Parkour': 13,
 'Wake_the_Robot': 14,
 'The_aquarium': 15,
 'UFO_crash_site_venue': 16,
 'Kowloon': 17,
 'Arena_Clash': 18,
 'Scifi_Sandbox': 19,
 'Super_Rumble': 20,
 'Slash_RPG': 21,
 'Pirate_Life': 22,
 'Zombie': 23,
 'Horizon_Boxing': 24,
 'VR_Classroom': 25,
 'Venues': 26,
 'Metdonalds': 27,
 '3D_Play_House': 28,
 'Out_Of_Control': 29,
 'Geometry_Gunners': 30,
 'Barnyard': 31,
 'Canyon_Runners': 32,
 'Titanic_Simulation': 33,
 'Creature_Feature': 34}

In [49]:
merged_df1['game_id'] = merged_df1['game_name'].map(game_abbs)

In [62]:
merged_df1.columns

Index(['game_name', 'user_id', 'order', 'timetodrop', 'dropped', 'age',
       'gender', 'pre_exp', 'game_id'],
      dtype='object')

In [63]:
analysis3=merged_df1[['user_id', 'order', 'timetodrop', 'dropped', 'age',
       'gender', 'pre_exp', 'game_id']]

In [64]:
analysis3['gender'] = analysis3['gender'].map({'Male': int(0), 'Female': int(1)})

In [65]:
analysis3

    user_id order  timetodrop  dropped age  gender           pre_exp  game_id
11      311     1          12        0  22     0.0        Not at all        1
12      309     1          10        1  21     1.0        Not at all        1
13      317     1          10        1  21     0.0              Once        1
15      315     1          12        0  35     0.0              Once        1
16      316     1          12        0  21     1.0              Once        1
..      ...   ...         ...      ...  ..     ...               ...      ...
798     294     1          12        0  24     0.0        Not at all       46
799     294     1          12        0  37     0.0              Once       46
801     298     1          12        1  24     0.0  Few times a year       46
802     292     1          12        0  24     1.0              Once       46
803     297     1          12        0  26     1.0  Few times a week       46

[423 rows x 8 columns]

In [69]:
analysis3['pre_exp'].value_counts()

Once                 198
Not at all           119
Few times a year      98
Few times a week       6
Few times a month      2
Name: pre_exp, dtype: int64

In [53]:
merged_df1['game_id'] = pd.factorize(merged_df1['game_name'])[0] + 1

In [77]:
df_combined.to_csv("analysis3.csv",index=False)

In [71]:
one_hot = pd.get_dummies(analysis3['pre_exp'])

In [72]:
one_hot['Others'] = one_hot[['Few times a week', 'Few times a month', 'Few times a year']].sum(axis=1)
one_hot.drop(['Few times a week', 'Few times a month', 'Few times a year'], axis=1, inplace=True)

In [73]:
one_hot

     Not at all  Once  Others
11            1     0       0
12            1     0       0
13            0     1       0
15            0     1       0
16            0     1       0
..          ...   ...     ...
798           1     0       0
799           0     1       0
801           0     0       1
802           0     1       0
803           0     0       1

[423 rows x 3 columns]

In [74]:
df_combined = pd.concat([analysis3, one_hot], axis=1)

In [76]:
df_combined.drop('pre_exp', axis=1)

,user_id,order,timetodrop,dropped,age,gender,game_id,Not at all,Once,Others
11,311,1,12,0,22,0.0,1,1,0,0
12,309,1,10,1,21,1.0,1,1,0,0
13,317,1,10,1,21,0.0,1,0,1,0
15,315,1,12,0,35,0.0,1,0,1,0
16,316,1,12,0,21,1.0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...
798,294,1,12,0,24,0.0,46,1,0,0
799,294,1,12,0,37,0.0,46,0,1,0
801,298,1,12,1,24,0.0,46,0,0,1
802,292,1,12,0,24,1.0,46,0,1,0
803,297,1,12,0,26,1.0,46,0,0,1

In [78]:
51/423

0.12056737588652482

## mean

In [4]:
df

,time,Thumb_L_sum,Thumb_R_sum,LE_speed_mean,LE_speed_median,LE_pos_change_sum,LE_pos_change_mean,LE_pos_change_median,Head_Speed_mean,Head_Speed_median,...,IndTrig_R,HandTrig_L,HandTrig_R,Thumb_L_x,Thumb_R_x,Thumb_L_y,Thumb_R_y,user_id,game_id,order
0,0,0.000000,3.594337,0.127828,0.090655,2.316057,0.020865,0.012802,0.172464,0.125845,...,0,32,0,0,3,0,3,5,1,2
1,1,33.093972,62.157799,0.063716,0.036334,3.967072,0.013448,0.005704,0.063247,0.036310,...,12,48,15,64,43,66,40,5,1,2
2,2,46.027865,90.608110,0.068397,0.042165,3.758526,0.009813,0.006048,0.067828,0.040388,...,4,62,37,100,63,93,70,5,1,2
3,3,18.430878,5.229467,0.068757,0.038978,3.775398,0.010068,0.005633,0.069725,0.037508,...,272,71,127,14,7,11,5,5,1,2
4,4,26.719036,1.597837,0.150314,0.117524,8.961758,0.022349,0.017352,0.153218,0.125837,...,203,27,157,22,5,21,5,5,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,103.000739,94.874378,0.034958,0.021215,2.608618,0.005598,0.003259,0.031584,0.021257,...,1,22,0,171,54,168,55,147,34,1
2930,8,53.928953,36.710560,0.043327,0.026262,2.421957,0.007295,0.004128,0.044183,0.025836,...,24,10,13,98,19,118,22,147,34,1
2931,9,45.495983,42.703410,0.026860,0.021454,1.126662,0.004471,0.003622,0.027040,0.021753,...,46,2,0,95,28,109,26,147,34,1
2932,10,17.765149,10.020055,0.123650,0.077568,5.506467,0.018858,0.012262,0.124227,0.078281,...,27,112,1,41,7,31,6,147,34,1
2933,11,6.148178,0.000000,0.063157,0.033172,1.521158,0.010074,0.005324,0.063689,0.038167,...,0,4,0,8,0,4,0,147,34,1

In [5]:
df.columns

Index(['time', 'Thumb_L_sum', 'Thumb_R_sum', 'LE_speed_mean',
       'LE_speed_median', 'LE_pos_change_sum', 'LE_pos_change_mean',
       'LE_pos_change_median', 'Head_Speed_mean', 'Head_Speed_median',
       'Head_pos_change_sum', 'Head_pos_change_mean', 'Head_pos_change_median',
       'Head_Velocity_Change_mean', 'Head_Velocity_Change_median',
       'Head_AngVel_Change_mean', 'Head_AngVel_Change_median', 'c_speed_mean',
       'c_speed_median', 'text_presence_sum', 'change in brightness_mean',
       'change in brightness_median', 'diff_HE_yaw_sum', 'diff_HE_yaw_mean',
       'diff_HE_yaw_median', 'diff_HE_roll_sum', 'diff_HE_roll_mean',
       'diff_HE_roll_median', 'diff_HE_pitch_sum', 'diff_HE_pitch_mean',
       'diff_HE_pitch_median', 'c_change_pitch_sum', 'c_change_pitch_mean',
       'c_change_pitch_median', 'c_change_roll_sum', 'c_change_roll_mean',
       'c_change_roll_median', 'c_change_yaw_sum', 'c_change_yaw_mean',
       'c_change_yaw_median', 'MS_rating_sum', 'hour_median', 'Buttons',
       'A_Pressed', 'IndTrig_L', 'IndTrig_R', 'HandTrig_L', 'HandTrig_R',
       'Thumb_L_x', 'Thumb_R_x', 'Thumb_L_y', 'Thumb_R_y', 'user_id',
       'game_id', 'order'],
      dtype='object')

In [33]:
col_names={'MS_rating_sum' : 'MS_rating',
'Thumb_L_sum' : 'Thumbstick_L',
'Thumb_R_sum' : 'Thumbstick_R',
'LE_speed_mean' : 'Eye_Speed',
'Head_Speed_mean' : 'Head_Speed',
'diff_HE_yaw_mean' : 'diff_Head_Eye_yaw',
'diff_HE_roll_mean' : 'diff_Head_Eye_roll',
'diff_HE_pitch_mean' : 'diff_Head_Eye_mean',
'IndTrig_L' : 'Index_Trig_L',
'IndTrig_R' : 'Index_Trig_R',
'c_change_pitch_mean' : 'camera_pitch',
'c_change_roll_mean' : 'camera_roll',
'c_change_yaw_mean' : 'camera_yaw',
'c_speed_mean' : 'camera speed',
'text_presence_sum' : 'text_presence',
'change in brightness_mean' : 'brightness_change',
'Buttons' : 'Buttons',
'A_Pressed' : 'Jumping',
'hour_median' : 'hour'}

In [34]:
df1=df[['time','MS_rating_sum','Thumb_L_sum', 'Thumb_R_sum',
'LE_speed_mean',
'Head_Speed_mean',
'diff_HE_yaw_mean',
'diff_HE_roll_mean',
'diff_HE_pitch_mean',
'IndTrig_L',
'IndTrig_R' ,
'c_change_pitch_mean',
'c_change_roll_mean',
'c_change_yaw_mean',
'c_speed_mean',
'text_presence_sum',
'change in brightness_mean',
'Buttons',
'A_Pressed',
'user_id',
'game_id',
'order',]]

In [35]:
df2 = df1.rename(columns=col_names)

In [36]:
df2

,time,MS_rating,Thumbstick_L,Thumbstick_R,Eye_Speed,Head_Speed,diff_Head_Eye_yaw,diff_Head_Eye_roll,diff_Head_Eye_mean,Index_Trig_L,...,camera_roll,camera_yaw,camera speed,text_presence,brightness_change,Buttons,Jumping,user_id,game_id,order
1,1,1.0,33.093972,62.157799,0.063716,0.063247,0.039889,0.166769,0.089614,8,...,0.222408,0.171433,107.561279,170.0,3.539671,10,10,5,1,2
2,2,1.0,46.027865,90.608110,0.068397,0.067828,0.070310,0.159780,0.088873,0,...,0.145371,0.118171,17.435567,374.0,5.606859,6,6,5,1,2
3,3,1.0,18.430878,5.229467,0.068757,0.069725,0.131197,0.508019,0.075576,23,...,0.063672,0.088050,10.550932,338.0,4.198118,8,0,5,1,2
4,4,1.0,26.719036,1.597837,0.150314,0.153218,0.150352,0.257278,0.079519,18,...,0.228013,0.107537,21.359123,345.0,8.341409,0,0,5,1,2
5,5,1.0,47.349634,26.812417,0.100103,0.100336,0.093609,0.267467,0.080504,80,...,0.094269,0.096619,11.013235,410.0,7.514897,10,10,5,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,2.0,103.000739,94.874378,0.034958,0.031584,0.016483,0.148175,0.108648,27,...,0.156540,0.227713,8.584673,466.0,2.331750,5,0,147,34,1
2930,8,5.0,53.928953,36.710560,0.043327,0.044183,0.046547,0.142530,0.115478,18,...,0.202115,0.328727,10.933816,332.0,3.597338,8,1,147,34,1
2931,9,4.0,45.495983,42.703410,0.026860,0.027040,0.007830,0.081415,0.103795,0,...,0.172831,0.226711,13.106737,252.0,2.057278,3,2,147,34,1
2932,10,3.0,17.765149,10.020055,0.123650,0.124227,0.077299,0.278264,0.132923,0,...,0.210364,0.265106,11.402999,292.0,1.317426,1,0,147,34,1
2933,11,5.0,6.148178,0.000000,0.063157,0.063689,0.123426,0.268676,0.187580,0,...,0.049544,0.221347,7.815273,151.0,2.934065,0,0,147,34,1

In [30]:
df

,time,Thumb_L_sum,Thumb_R_sum,LE_speed_mean,LE_speed_median,LE_pos_change_sum,LE_pos_change_mean,LE_pos_change_median,Head_Speed_mean,Head_Speed_median,...,HandTrig_R,Thumb_L_x,Thumb_R_x,Thumb_L_y,Thumb_R_y,user_id,game_id,order,Intensity,panel_id
0,0,0.000000,3.594337,0.127828,0.090655,2.316057,0.020865,0.012802,0.172464,0.125845,...,0,0,3,0,3,5,1,2,M,1005
1,1,33.093972,62.157799,0.063716,0.036334,3.967072,0.013448,0.005704,0.063247,0.036310,...,15,64,43,66,40,5,1,2,M,1005
2,2,46.027865,90.608110,0.068397,0.042165,3.758526,0.009813,0.006048,0.067828,0.040388,...,37,100,63,93,70,5,1,2,M,1005
3,3,18.430878,5.229467,0.068757,0.038978,3.775398,0.010068,0.005633,0.069725,0.037508,...,127,14,7,11,5,5,1,2,M,1005
4,4,26.719036,1.597837,0.150314,0.117524,8.961758,0.022349,0.017352,0.153218,0.125837,...,157,22,5,21,5,5,1,2,M,1005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,103.000739,94.874378,0.034958,0.021215,2.608618,0.005598,0.003259,0.031584,0.021257,...,0,171,54,168,55,147,34,1,M,34147
2930,8,53.928953,36.710560,0.043327,0.026262,2.421957,0.007295,0.004128,0.044183,0.025836,...,13,98,19,118,22,147,34,1,M,34147
2931,9,45.495983,42.703410,0.026860,0.021454,1.126662,0.004471,0.003622,0.027040,0.021753,...,0,95,28,109,26,147,34,1,M,34147
2932,10,17.765149,10.020055,0.123650,0.077568,5.506467,0.018858,0.012262,0.124227,0.078281,...,1,41,7,31,6,147,34,1,M,34147
2933,11,6.148178,0.000000,0.063157,0.033172,1.521158,0.010074,0.005324,0.063689,0.038167,...,0,8,0,4,0,147,34,1,M,34147

In [32]:
df=df[df['time']>0]

In [50]:
df2

,time,MS_rating,Thumbstick_L,Thumbstick_R,Eye_Speed,Head_Speed,diff_Head_Eye_yaw,diff_Head_Eye_roll,diff_Head_Eye_mean,Index_Trig_L,...,camera speed,text_presence,brightness_change,Buttons,Jumping,user_id,game_id,order,Intensity,panel_id
1,1,1.0,33.093972,62.157799,0.063716,0.063247,0.039889,0.166769,0.089614,8,...,107.561279,170.0,3.539671,10,10,5,1,2,M,1005
2,2,1.0,46.027865,90.608110,0.068397,0.067828,0.070310,0.159780,0.088873,0,...,17.435567,374.0,5.606859,6,6,5,1,2,M,1005
3,3,1.0,18.430878,5.229467,0.068757,0.069725,0.131197,0.508019,0.075576,23,...,10.550932,338.0,4.198118,8,0,5,1,2,M,1005
4,4,1.0,26.719036,1.597837,0.150314,0.153218,0.150352,0.257278,0.079519,18,...,21.359123,345.0,8.341409,0,0,5,1,2,M,1005
5,5,1.0,47.349634,26.812417,0.100103,0.100336,0.093609,0.267467,0.080504,80,...,11.013235,410.0,7.514897,10,10,5,1,2,M,1005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,2.0,103.000739,94.874378,0.034958,0.031584,0.016483,0.148175,0.108648,27,...,8.584673,466.0,2.331750,5,0,147,34,1,M,34147
2930,8,5.0,53.928953,36.710560,0.043327,0.044183,0.046547,0.142530,0.115478,18,...,10.933816,332.0,3.597338,8,1,147,34,1,M,34147
2931,9,4.0,45.495983,42.703410,0.026860,0.027040,0.007830,0.081415,0.103795,0,...,13.106737,252.0,2.057278,3,2,147,34,1,M,34147
2932,10,3.0,17.765149,10.020055,0.123650,0.124227,0.077299,0.278264,0.132923,0,...,11.402999,292.0,1.317426,1,0,147,34,1,M,34147
2933,11,5.0,6.148178,0.000000,0.063157,0.063689,0.123426,0.268676,0.187580,0,...,7.815273,151.0,2.934065,0,0,147,34,1,M,34147

In [53]:
# # Create dummy variables
# dummy_df = pd.get_dummies(df2['Intensity'])

# # Concatenate dummy variables with original DataFrame
# df3 = pd.concat([df2, dummy_df], axis=1)

# Drop the original categorical variable
df3.drop('Intensity', axis=1, inplace=True)

print(df3)

      time  MS_rating  Thumbstick_L  Thumbstick_R  Eye_Speed  Head_Speed  \
1        1        1.0     33.093972     62.157799   0.063716    0.063247
2        2        1.0     46.027865     90.608110   0.068397    0.067828
3        3        1.0     18.430878      5.229467   0.068757    0.069725
4        4        1.0     26.719036      1.597837   0.150314    0.153218
5        5        1.0     47.349634     26.812417   0.100103    0.100336
...    ...        ...           ...           ...        ...         ...
2929     7        2.0    103.000739     94.874378   0.034958    0.031584
2930     8        5.0     53.928953     36.710560   0.043327    0.044183
2931     9        4.0     45.495983     42.703410   0.026860    0.027040
2932    10        3.0     17.765149     10.020055   0.123650    0.124227
2933    11        5.0      6.148178      0.000000   0.063157    0.063689

      diff_Head_Eye_yaw  diff_Head_Eye_roll  diff_Head_Eye_mean  Index_Trig_L  \
1              0.039889            0.166769            0.089614             8
2              0.070310            0.159780            0.088873             0
3              0.131197            0.508019            0.075576            23
4              0.150352            0.257278            0.079519            18
5              0.093609            0.267467            0.080504            80
...                 ...                 ...                 ...           ...
2929           0.016483            0.148175            0.108648            27
2930           0.046547            0.142530            0.115478            18
2931           0.007830            0.081415            0.103795             0
2932           0.077299            0.278264            0.132923             0
2933           0.123426            0.268676            0.187580             0

      ...  brightness_change  Buttons  Jumping  user_id  game_id  order  \
1     ...           3.539671       10       10        5        1      2
2     ...           5.606859        6        6        5        1      2
3     ...           4.198118        8        0        5        1      2
4     ...           8.341409        0        0        5        1      2
5     ...           7.514897       10       10        5        1      2
...   ...                ...      ...      ...      ...      ...    ...
2929  ...           2.331750        5        0      147       34      1
2930  ...           3.597338        8        1      147       34      1
2931  ...           2.057278        3        2      147       34      1
2932  ...           1.317426        1        0      147       34      1
2933  ...           2.934065        0        0      147       34      1

      panel_id  C  I  M
1         1005  0  0  1
2         1005  0  0  1
3         1005  0  0  1
4         1005  0  0  1
5         1005  0  0  1
...        ... .. .. ..
2929     34147  0  0  1
2930     34147  0  0  1
2931     34147  0  0  1
2932     34147  0  0  1
2933     34147  0  0  1

[2645 rows x 26 columns]

In [54]:
df3

,time,MS_rating,Thumbstick_L,Thumbstick_R,Eye_Speed,Head_Speed,diff_Head_Eye_yaw,diff_Head_Eye_roll,diff_Head_Eye_mean,Index_Trig_L,...,brightness_change,Buttons,Jumping,user_id,game_id,order,panel_id,C,I,M
1,1,1.0,33.093972,62.157799,0.063716,0.063247,0.039889,0.166769,0.089614,8,...,3.539671,10,10,5,1,2,1005,0,0,1
2,2,1.0,46.027865,90.608110,0.068397,0.067828,0.070310,0.159780,0.088873,0,...,5.606859,6,6,5,1,2,1005,0,0,1
3,3,1.0,18.430878,5.229467,0.068757,0.069725,0.131197,0.508019,0.075576,23,...,4.198118,8,0,5,1,2,1005,0,0,1
4,4,1.0,26.719036,1.597837,0.150314,0.153218,0.150352,0.257278,0.079519,18,...,8.341409,0,0,5,1,2,1005,0,0,1
5,5,1.0,47.349634,26.812417,0.100103,0.100336,0.093609,0.267467,0.080504,80,...,7.514897,10,10,5,1,2,1005,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,7,2.0,103.000739,94.874378,0.034958,0.031584,0.016483,0.148175,0.108648,27,...,2.331750,5,0,147,34,1,34147,0,0,1
2930,8,5.0,53.928953,36.710560,0.043327,0.044183,0.046547,0.142530,0.115478,18,...,3.597338,8,1,147,34,1,34147,0,0,1
2931,9,4.0,45.495983,42.703410,0.026860,0.027040,0.007830,0.081415,0.103795,0,...,2.057278,3,2,147,34,1,34147,0,0,1
2932,10,3.0,17.765149,10.020055,0.123650,0.124227,0.077299,0.278264,0.132923,0,...,1.317426,1,0,147,34,1,34147,0,0,1
2933,11,5.0,6.148178,0.000000,0.063157,0.063689,0.123426,0.268676,0.187580,0,...,2.934065,0,0,147,34,1,34147,0,0,1

In [57]:
df3.to_csv("panel_mean.csv", index=False)

## dropped out

In [4]:
dropped= pd.read_csv("/home/dinithi/MSRatingSummary1.csv")

In [5]:
pwd

'/home/dinithi/vr-motion-sickness-modelling/Data_Pre_Processing'

In [6]:
dropped

,Session,MS_rating,mean_MSR
0,181_1_Barbie,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.000000
1,184_1_Barbie,"[2.0, 1.0, 2.0, 2.0, 1.0, 3.0, 3.0, 3.0, 3.0, ...",2.384615
2,178_1_Barbie,"[1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.384615
3,183_1_Barbie,"[1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 1.0, ...",1.230769
4,187_1_Barbie,"[1.0, 1.0, 2.0, 3.0, 2.0, 3.0, 1.0, 1.0, 1.0, ...",1.769231
...,...,...,...
788,294_1_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.000000
789,289_2_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.000000
790,298_1_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 2.0, 3.0, 3.0, 3.0, 4.0, 4.0, ...",3.000000
791,292_1_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, ...",1.461538
792,297_1_Man_of_Moon_Mountain,"[1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 2.0, 2.0, ...",1.692308

In [7]:
arrs=dropped['MS_rating'].to_list()

In [8]:
import pandas as pd
import ast
df=dropped

# Assuming your data is stored in a DataFrame called df

# Convert the string representations of lists to actual lists
df['MS_rating'] = df['MS_rating'].apply(ast.literal_eval)

# Filter out rows where the length of the list in 'MS_rating' is not equal to 13
filtered_df = df[df['MS_rating'].apply(len) <13]

# Extract the 'MS_rating' column from the filtered DataFrame
ms_ratings = filtered_df['MS_rating']

print(ms_ratings)

12     [1.0, 2.0, 2.0, 2.0, 2.0, 3.0, 2.0, 2.0, 2.0, ...
13     [2.0, 1.0, 2.0, 3.0, 2.0, 3.0, 4.0, 4.0, 4.0, ...
29         [1.0, 1.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0]
30     [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
40     [1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 3.0, ...
                             ...
759    [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, ...
761                                                [1.0]
766                                                [1.0]
767                                                [1.0]
770                                           [1.0, 1.0]
Name: MS_rating, Length: 137, dtype: object

In [9]:
filtered_df

,Session,MS_rating,mean_MSR
12,309_1_Escape_Puzzle_Mansion,"[1.0, 2.0, 2.0, 2.0, 2.0, 3.0, 2.0, 2.0, 2.0, ...",2.454545
13,317_1_Escape_Puzzle_Mansion,"[2.0, 1.0, 2.0, 3.0, 2.0, 3.0, 4.0, 4.0, 4.0, ...",3.250000
29,333_2_Spy_School,"[1.0, 1.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0]",2.444444
30,339_1_Spy_School,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",1.000000
40,357_1_Circle_Kawaii,"[1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 3.0, ...",2.000000
...,...,...,...
759,107_1_Pirate_Life,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, ...",1.166667
761,75_1_Superhero_Arena,[1.0],1.000000
766,82_1_Superhero_Arena,[1.0],1.000000
767,74_1_Superhero_Arena,[1.0],1.000000
770,77_1_Superhero_Arena,"[1.0, 1.0]",1.000000

In [18]:
MSR= filtered_df['MS_rating'].to_list()
sess= filtered_df['Session'].to_list()

MSR1=[]
sess1=[]
path=[]
for i in range(len(MSR)):
    game_name = sess[i].split("_", 2)[-1]
    pathth=os.path.join(game_name,sess[i])
    if MSR[i][-1]== 5:
        MSR1.append(MSR[i])
        sess1.append(sess[i])
        path.append(pathth)
        print(i)
    if MSR[i][-1]== 4:
        MSR1.append(MSR[i])
        sess1.append(sess[i])
        path.append(pathth)
        
        print(i)
        print('****')

0
1
4
****
6
7
8
9
10
11
12
13
14
15
16
17
19
22
23
24
27
28
29
****
31
32
33
41
42
43
48
49
51
52
53
54
55
****
56
57
58
59
****
60
65
66
69
70
71
73
****
74
75
77
78
****
79
85
86
88
89
90
92
96
101
102
103
104
****
107
108
110
111
114
115
116
118
****
119
****
121
122
125
127
128
130
131

In [ ]:
def pathf(name):

In [15]:
input_string = "309_1_Escape_Puzzle_Mansion"

# Splitting the string by underscore and getting the last part
game_name = input_string.split("_", 2)[-1]

In [16]:
game_name

'Escape_Puzzle_Mansion'

In [21]:
dfd = pd.DataFrame(sess1, columns=['session'])

In [22]:
dfd

                        session
0   309_1_Escape_Puzzle_Mansion
1   317_1_Escape_Puzzle_Mansion
2           357_1_Circle_Kawaii
3           351_2_Circle_Kawaii
4             302_1_New_Olympus
..                          ...
73       165_2_Geometry_Gunners
74       163_2_Geometry_Gunners
75         338_2_Jail_Simulator
76         333_1_Jail_Simulator
77            106_1_Pirate_Life

[78 rows x 1 columns]

In [23]:
dfd["MS_rating"]=MSR1

In [28]:
dfd['path']=dfd['path']+'/data_file.csv'

In [29]:
dfd

,session,MS_rating,path
0,309_1_Escape_Puzzle_Mansion,"[1.0, 2.0, 2.0, 2.0, 2.0, 3.0, 2.0, 2.0, 2.0, ...",Escape_Puzzle_Mansion/309_1_Escape_Puzzle_Mans...
1,317_1_Escape_Puzzle_Mansion,"[2.0, 1.0, 2.0, 3.0, 2.0, 3.0, 4.0, 4.0, 4.0, ...",Escape_Puzzle_Mansion/317_1_Escape_Puzzle_Mans...
2,357_1_Circle_Kawaii,"[1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 3.0, ...",Circle_Kawaii/357_1_Circle_Kawaii/data_file.csv
3,351_2_Circle_Kawaii,"[1.0, 2.0, 3.0, 4.0, 4.0, 5.0]",Circle_Kawaii/351_2_Circle_Kawaii/data_file.csv
4,302_1_New_Olympus,"[1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 3.0, ...",New_Olympus/302_1_New_Olympus/data_file.csv
...,...,...,...
73,165_2_Geometry_Gunners,"[2.0, 4.0, 4.0, 4.0, 5.0, 4.0, 4.0, 5.0, 5.0, ...",Geometry_Gunners/165_2_Geometry_Gunners/data_f...
74,163_2_Geometry_Gunners,"[1.0, 2.0, 3.0, 4.0, 5.0]",Geometry_Gunners/163_2_Geometry_Gunners/data_f...
75,338_2_Jail_Simulator,"[1.0, 2.0, 2.0, 3.0, 4.0, 5.0]",Jail_Simulator/338_2_Jail_Simulator/data_file.csv
76,333_1_Jail_Simulator,"[1.0, 3.0, 3.0, 3.0, 3.0, 4.0, 5.0]",Jail_Simulator/333_1_Jail_Simulator/data_file.csv
77,106_1_Pirate_Life,"[1.0, 2.0, 3.0, 4.0, 3.0, 4.0, 4.0, 3.0, 3.0, ...",Pirate_Life/106_1_Pirate_Life/data_file.csv

In [30]:
dfd.to_csv('Dropped_out_sessions.csv',index=False)

In [ ]:
os.listdir()